### ISSUE TITLE
Router arguments aren't urldecoded

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#102]
Dispatch callables get the following arguments passed: `Request, Response, array` where array is an associative array of the route arguments. The values there aren't URL decoded but instead still encoded. I think these should be provided in a decoded way.

**Comment by bwoebi** [comment]
I wonder where exactly we shall decode the path? If we decode before _before_ the URL has been routed, we won't have different routes for `/%74est` and `/test`. (But e.g. ``
If we indeed decode before, should InternalRequest->uriPath contain the rawurldecoded route? Should InternalRequest->uri be `rawurldecode($uri["path"])."/".$uri["query"]`? Or still be `$uri["path"]."/".$uri["query"]`?

I haven't thought it throughly yet, but Think
