### ISSUE TITLE
Many errors in tests after clone

### ISSUE THREAD

**Issue by samizdam** [amphp/aerys#108]
Hi! 

I'm fork aerys and get many errors after run tests via vendor/bin/phpunit
Summary:
```
ERRORS!
Tests: 535, Assertions: 41969, Errors: 3, Failures: 1, Warnings: 25, Skipped: 8.
```

Full phpunit output here: http://pastebin.com/2nJdjH3H
Installation log here: http://pastebin.com/Zf46iyMB

It's normal?

**Comment by staabm** [comment]
The travis ci build is green, so it seems something is fishy.

**Comment by bwoebi** [comment]
That's a bug in a phpunit dependency, wait a few hours until @sebastianbergmann has fixed it.

It's all fine with Aerys itself.

**Comment by krakjoe** [comment]
FYI https://github.com/sebastianbergmann/phpunit/pull/2356

**Comment by bwoebi** [comment]
@krakjoe No, not that (Aerys tests aren't using process insulation anyway). We're talking about sebastianbergmann/recursion-context#5.

**Comment by krakjoe** [comment]
Oh I see, I missed that ...

**Comment by bwoebi** [comment]
Was fixed upstream; closing here.
