### ISSUE TITLE
How to register final exception handler

### ISSUE THREAD

**Issue by strayobject** [amphp/aerys#110]
I want to return a response with status 500 and json body, say for an uncaught exception. Right now I'm getting html from Aerys\genericResponseFilter().
Is there a way to register a handler somewhere? If so could you please tell me where?

Right now, the only working option I have are:
 - catch throwable in every single controller
 - wrap each controller in a proxy one which would catch any throwable and convert it to a properly formatted response
 - extend existing http driver class and replace the genericResponseFilter method with one of my own.

Would this be a preferrable/right way of doing this:
 - register a middleware which will add my own filter to the http driver

Is my filter going to be called before the generic one?

**Comment by kelunik** [comment]
Currently, you get the following response on uncaught exceptions: https://github.com/amphp/aerys/blob/6335cc224e54999185119a28684804e91be458ae/lib/Server.php#L897-L918. I think the only current way to return a different response there is to register a middleware that checks the status code and returns a different response.

I think we should add a dedicated exception handler that can turn specific exceptions into responses.

**Comment by strayobject** [comment]
Thanks for correcting me. I know how to register middlewares that run before responder code is called, but how can I register one that runs after?

**Comment by kelunik** [comment]
You can do that with [`Middleware::do`](http://amphp.org/docs/aerys/classes/middleware.html#dointernalrequest-generatornull). You can check the status there and just override the response body.

**Comment by bwoebi** [comment]
@strayobject Yes, that's right, non-blocking architectures involving Promises encourage a much flatter code structure with less nested calls, no I/O calls in constructors etc., by design (as you always need to pass Promises back (or `yield from`) through the chain). [That's not necessarily a bad thing, it just forces you to give your architecture more thought and may lead to an overall better architecture.]

In general, I wonder what we want here:
- globally configurable, once for the whole Server (would be a static setter in Host then probably)
- per-host exception handlers (an Host::except() method accepting a single callback)
- flexible exception handling, everywhere (an extra Interface (like Middleware, Bootable, ...) for usage within use(), and perhaps a high-level Router::except() method)

What exactly shall we pick?

**Comment by kelunik** [comment]
> non-blocking architectures involving Promises encourage a much flatter code structure with less nested calls

Not really. You just return a promise everywhere you want to potentially do I/O.

**Comment by bwoebi** [comment]
@kelunik What is your preferred way of handling that?

I'd personally use per-host exception handlers. This would allow e.g. error responses matching the layout of the general host. (without having to defacto re-implement virtual host dispatching yourself)

In the more unlikely case you need routed error handlers, you always can use `->except(new Router->get("/blog/{path:.*}", function(…) { … })->get("/{path:.*}", function(…) { … }))`.

**Comment by lukaszwit** [comment]
In my opinion it would be nice to have similar approuch like 
[in silex](http://silex.sensiolabs.org/doc/master/usage.html#error-handlers)
I'm imagine that Host could have method "error" with some callback pointing what exception we're interested in.

**Comment by kelunik** [comment]
I think we need two different things, one handler to log exceptions if output already started and another one that can actually send a response body.

We could continue to use `Host::use` and add a `ErrorHandler` or `ErrorResponder` interface, but that wouldn't allow to use different handlers for different exceptions. I guess people shouldn't use exceptions to choose the error responder anyway. If they need it, they can build something like that on top or said interface.

**Comment by kelunik** [comment]
This will be solved with the new middlewares we plan. Watch #156. The current middlewares will be renamed to `Filter` and are only for low-level filtering and processing.
