### ISSUE TITLE
Allow Router to accept multiple HTTP methods at once for a route

### ISSUE THREAD

**Issue by broiniac** [amphp/aerys#113]
Let's say I want to build subpage with form. Let's call it `/product/create`. I also want to handle both subpage display as well as form handling in one callable. Here is my code for routing definition:
```
        $router = router();
        $router->route(
            'GET', //method
            '/product/create', //url
            'App\\Controllers\\ProductController::createAction' //callable
        );
        $router->route(
            'POST', //method
            '/product/create', //url
            'App\\Controllers\\ProductController::createAction' //callable
        );
```
I think it's best way right now (besides using $router->post() / $router->get() methods);

$router->route() method itself as first parameter takes string. I believe router will be more coder-friendly, if it will be allowed to send array of methods as first param as well as string.

Example below:
```
        $router = router();
        $router->route(
            ['GET', 'POST'], //CHANGE HERE: methods array
            '/product/create', //url
            'App\\Controllers\\ProductController::createAction' //callable
        );
        $router->route(
            'GET', //REGULAR WAY SHOULD WORK AS WELL
            '/product/show, //url
            'App\\Controllers\\ProductController::showAction' //callable
        );
```

I will create pull request with proposed changes in few minutes.

**Comment by kelunik** [comment]
Having one handler doing multiple things is against the single responsibility principle. I'm against making it easier to do the wrong thing.

**Comment by bwoebi** [comment]
@kelunik It depends on what you want to do there, whether it violates SRP or not.

It's quite a common request, and I feel like we should honor it.

**Comment by kelunik** [comment]
@broiniac Why do you have multiple methods registered to one handler? What's the use case?

**Comment by kelunik** [comment]
@bwoebi There are very few things that don't violate the SRP, one example is making an alias like `POST` → `PATCH` like Twitter does, but such things are better handled by just defining a middleware that changes the request method.

**Comment by broiniac** [comment]
@kelunik As I said before, example use case might be situation, when I want to handle both display and form handling in one callable hidden under same url.

If it's violating SRP in that way, there always can be some separate method for this one, like "routeWithManyMethods" or simple "routes" (name of the latter can be confusing though).

@bwoebi I believe it's common request, because all major "normal" frameworks and routers have this feature built-in (like Symfony via `sensio/framework-extra-bundle`, as well as `nikic/FastRoute`, and so on). Even so, if You guys think it's no-go, then just don't agree. Few extra lines of code won't hurt anyone. Furthermore, lack of this feature might somehow require, to build cleaner code.

**Comment by kelunik** [comment]
> If it's violating SRP in that way, there always can be some separate method for this one, like "routeWithManyMethods" or simple "routes" (name of the latter can be confusing though).

I meant that if you have a handler that reacts to two HTTP methods, _that's_ violating SRP. The handler does both, show the HTML _and_ handle the form submission.

Usually I think this is better solved by having the display logic as a dependency of the processor, so the processor can delegate to the display logic if an error occurs.

That way you can wrap the form handling separately from the pure display logic, e.g. add a rate limit to submissions or authorization checks on a higher level.

> Furthermore, lack of this feature might somehow require, to build cleaner code.

That's basically my argument against it.

**Comment by rdlowrey** [comment]
I've argued against this behavior strenuously in the FastRoute library ... I really prefer not to add it in aerys

**Comment by bwoebi** [comment]
Fine, we're rejecting that for now.

Thank for your contribution though, feedback and further requests are always welcome though. :-)
