### ISSUE TITLE
Fix warnings in tests

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#116]
Currently we get a lot of warnings, because we're using a deprecated PHPUnit API.

`PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead`

**Comment by PeeHaa** [comment]
Not sure if anybody is working on these yet, but it looks like something I can pick up when I have some spare time.

**Comment by kelunik** [comment]
Not sure, I think it's fixed in the `amp_v2` branch, @trowski?
