### ISSUE TITLE
Can't install amphp/parallel alongside aerys

### ISSUE THREAD

**Issue by withinboredom** [amphp/aerys#118]
Use case: websocket services which need threading to do blocking operations in the background.

I get this when trying to install:

```
Problem 1
    - Can only install one of: amphp/amp[2.0.x-dev, v1.x-dev].
    - Can only install one of: amphp/amp[v1.x-dev, 2.0.x-dev].
    - Can only install one of: amphp/amp[2.0.x-dev, v1.x-dev].
```

**Comment by kelunik** [comment]
What kind of blocking operations do you want to do?

`amphp/parallel` doesn't have a release yet.

**Comment by withinboredom** [comment]
I'm waiting to be notified of a change via changefeed from rethinkdb.

**Comment by kelunik** [comment]
You should probably do that in a separate process and use a pubsub system like Redis to notify all your websocket endpoints instead of using threads for that.

I don't know about the protocol, but you can probably implement it without blocking, too?

**Comment by withinboredom** [comment]
That's what a changefeed is, a subscription on a query. I'll try to see if there's some way to not block.

**Comment by kelunik** [comment]
Which client do you currently use?

**Comment by bwoebi** [comment]
@withinboredom This repository has an amp_v2 branch, which you may want to check out, for usage in conjunction with amphp/parallel.

**Comment by kelunik** [comment]
Closing this one, as `amp_v2` has been mentioned.
