### ISSUE TITLE
Getting ip from websocket

### ISSUE THREAD

**Issue by withinboredom** [amphp/aerys#120]
I've been having trouble getting the ip address of a given client id, which is particularly important if you need to log certain actions related to payments, etc. Any tips would be greatly appreciated.

**Comment by kelunik** [comment]
You can have a look at https://github.com/kelunik/demo-chat/blob/3a27358972c1a9d6ac4d96147ee928e449568e2f/src/Chat.php#L36 to see how to get the client IP. I'll review our documentation soon and add it if it's missing there.

**Comment by withinboredom** [comment]
Thanks for the quick response, that was exactly what I needed!

**Comment by kelunik** [comment]
I added an example to http://amphp.org/docs/aerys/websocket/handshake.html, but it's probably not the right place to explain it. Where did you expect to find this information?

**Comment by bwoebi** [comment]
@kelunik It applies to Request object in general. There's no direct mention of it in the tutorial. Now you added it, but it should be probably added to the general http(-advanced??) docs.
