### ISSUE TITLE
Making Request and Response compatible with PSR-7

### ISSUE THREAD

**Issue by lukaszwit** [amphp/aerys#121]
I'm sure we alle heard about PSR-7.
Most frameworks nowadays uses this standard or provides some kind of bridge to allow use it.
I think it would much extend ease to use Aerys by being compatible with PSR-7. I'm thinking here about routing and middlewares especially.
Would that be even possible with aerys?

**Comment by bwoebi** [comment]
Looks like all the discussions about this haven't been inside an issue here.

Well, the quick answer is: no.

---

The long answer: There are multiple issues, apart from performance:

- `getBody()`: returns a StreamInterface, as well as `withBody(StreamInterface)`. StreamInterfaces expect the whole data to be present ahead of time (or in a file), but you cannot dynamically update the Stream after sending data. So, when the server code would call `StreamInterface::getContents()`, you get _that_ data present at that time. Applies also to request - we'd need to buffer the whole thing first. So good luck implementing a long stream of data with this.
- `getUploadedFiles()` uses UploadedFileInterface … there is no such thing in Aerys. if you use `Aerys\parseBody()` on the body, you get the files as normal keys with a few metadata (like content-type or filename) [which is what files really are] - and in Aerys responder callables are started when the 
- When a request arrives, the responder is immediately invoked after headers. Then the responder may decide e.g. on how big the request data may be, again, this will not work with streams.
- Additionally, also for implementation reasons (allowing the incremental parsing) we do not understand the concept of array keys. Keys with the same name are put into an one-dimensional array.

There have been suggestions to handle streams separately - but then there are still the differences regarding files or array keys....

Basically: PSR-7 is inherently designed for synchronous contexts.

You can throw away all the advantages of async and build a function wrapping your callable to convert from and to Aerys Request and Response objects - that'll be (apart from being slower) actually fine for a large part of the routes (no files, no streaming) - but not all. It means - buffering everything first, then calling the responder, and then sending all at once. We need to provide our implementation for the use cases which need it.

In a normal web application, you can simply choose to not use PSR-7 for a specific case, e.g. if you need streaming, then you just print as data arrives and ignore PSR-7 for that single script.
If we'd use PSR-7 by default in Aerys, you have no real way to go back to a fully featured version; while you should be able to convert the Aerys implementation to PSR-7.

You could write your own implementation of Aerys\Router which will use PSR-7. If it solves all your needs…
But for the before mentioned reasons, we cannot provide PSR-7 natively here.
