### ISSUE TITLE
Evict realpath cache

### ISSUE THREAD

**Issue by staabm** [amphp/aerys#122]
As we recently learned in our room11 discussion, the php-src realpath cache eviction works only suboptimal.

Would it make sense to use some kind of timer/request count based check which verifies that the realpath cache is not full or triggers cache clear.

This just to make sure that no unnecessary file io happens within php-src because of a filled realpath-cache

**Comment by kelunik** [comment]
Could you link the discussion? I think that's something that should be solved in `php-src` rather than with hacks here. How would we clear that cache?

**Comment by staabm** [comment]
It will finally be solved in php-src but it feels like we should have a solution in userland as not everybody will use the latest versions

**Comment by staabm** [comment]
http://chat.stackoverflow.com/transcript/message/34952738#34952738 Starting 5:32 PM

**Comment by kelunik** [comment]
@staabm We're not the kind of developers working around every possible issue if it's not important. We did something for PHP 5.6 TLS in `amphp/socket`, but generally we just require the newer PHP versions then.

If it only hits performance a little bit in earlier versions, that's fine with me.

**Comment by staabm** [comment]
it will lead to lots of IO when the cache is full... we could also emit a warning or document how people should configure the php-ini setting properly

**Comment by kelunik** [comment]
@staabm What's the current state @ php-src?

**Comment by staabm** [comment]
As far as I remember we increased a lot of default settings so the peoblem does not happen that often, see https://github.com/php/php-src/pull/2271

The eviction strategy wasn changed, see https://php-lxr.adamharvey.name/source/xref/master/Zend/zend_virtual_cwd.c#632

The bug still is a thing see https://bugs.php.net/bug.php?id=73887

**Comment by staabm** [comment]
Ot sure whether @krakjoe @nikic or @bwoebi will find some time to work on the eviction strategy

**Comment by kelunik** [comment]
The current implementation just doesn't evict at all, but just doesn't store any new entries in case the cache is full. https://github.com/php/php-src/blob/2cfd64cad856324eead686724d12cb11a1859ab6/Zend/zend_virtual_cwd.c#L625

**Comment by nikic** [comment]
If you want to see movement on this, I would suggest implementing some self-contained representative stress-tests that can be used to gauge the quality of any solution we may implement. I think there are some very simple improvements we can make (e.g. discard fixed percentage of LRU on full cache), but we need something to test against. Maybe it's possible to collect a trace of all realpath cache accesses for a couple of cases where you are currently observing degraded performance attributable to realpath cache misses?

**Comment by bwoebi** [comment]
I don't think we need a particularly high quality solution, a trivial LRU should really be enough here I assume.
A simple LRU will be already a vast improvement over no eviction at all upon full cache.

**Comment by kelunik** [comment]
I implemented a simple round robin eviction, see https://github.com/php/php-src/pull/2407.

**Comment by kelunik** [comment]
I'm going to close this. I haven't seen real world problems yet. If they occur, please add them to the bug reports and issues that exist for php-src.
