### ISSUE TITLE
Disable host / port match for single host applications

### ISSUE THREAD

**Issue by lukaszwit** [amphp/aerys#124]
Is there any way to use aerys server without host name (by ip). 

```php
(new Aerys\Host)
    ->expose('0.0.0.0', 8089)
    // ... ->use
```
In this case aerys will assign "localhost" name by default but I need to access to it (API) without any host name just by some IP and port. When I'm trying to access it I get an error:
```html
<html>
<body>
<h1>400 Bad Request</h1>

<hr/>
<em>Thu, 12 Jan 2017 17:17:02 GMT</em>
<br/><br/>
</body>
</html>
```

My server logs looks like this:
```
2017-01-12T17:11:19.508998817Z [2017-01-12 17:11:19] debug accept 172.17.0.1:53013
2017-01-12T17:11:19.509241443Z [2017-01-12 17:11:19] debug GET /status HTTP/1.1 @ 172.17.0.1:53013
2017-01-12T17:11:19.509781032Z [2017-01-12 17:11:19] debug close 172.17.0.1:53013
```
Any hint?

**Comment by kelunik** [comment]
@lukaszwit This doesn't happen any longer with the latest changes. Dunno if there's a release yet.

**Comment by kelunik** [comment]
See https://github.com/amphp/aerys/commit/25ebac2702411db8e4db7de4b80609c94739700a

**Comment by bwoebi** [comment]
Or basically, update your Aerys version to 0.4.4.

**Comment by lukaszwit** [comment]
@bwoebi I'm already on 0.4.4
This is my composer.lock:
```json
            "name": "amphp/aerys",
            "version": "v0.4.4",
            "source": {
                "type": "git",
                "url": "https://github.com/amphp/aerys.git",
                "reference": "de8bc2f93bd1407c5762ac7ed88ebf14b5b9add7"
            }
```

Setting empty name also doesn't resolve problem
```php
(new Aerys\Host)
->name('')
->expose('0.0.0.0', 8089)
;
```

When I put the name and run locally it runs perfectly.

**Comment by kelunik** [comment]
@lukaszwit Works fine for me, both on `http://localhost:1337/` and on `http://test.localhost:1337/` with `bin/aerys -c demo.php`.

**Comment by bwoebi** [comment]
@lukaszwit I cannot reproduce your issue either :-(

Could you please try to debug a bit yourself?
The host selection happens in `Aerys\VhostContainer`.
With that configuration `isset($this->vhosts[$wildcardHost])` should return true.

Otherwise, could you please dump the `$this->vhosts` array there and tell me its contents?

**Comment by lukaszwit** [comment]
Thanks for your hints.
I've manage to find out that the port is a problem for me. I'm running aerys in docker which is running in vm. Aerys exposing port 8089 but from my host machine it is mapped to some random port (3xxxx). So in Aerys\VhostContainer::selectHostByAuthority my wildcart hosts are
0.0.0.0:32502, [::]:32502 but aerys knows only about port 8089 exposed in code. 
Not sure what to do yet.. The IP address and port number changes on each deploy - I cannot hardcode it.

**Comment by rdlowrey** [comment]
When I originally implemented HTTP's strict virtual hostname resolution rules I followed them to the letter. There are times, though, when not requiring a perfect match is desirable (e.g. this case). We should at least allow users to optionally enable matches. We can add some kind of setting for this ...

**Comment by lukaszwit** [comment]
Maybe it's not typical situation - I'm accessing aerys app via http://192.168.64.2:32502 but it listenes on 8089 (and receives traffic). The port in my URL has nothing to do with real port that app is listening to (yes strange but normal in kubernetes cluster). Is there any way for aerys to find out the real port on which it receives the traffic?
I could use DNS SRV record for assigning host name that will cover port too but... I think that when I define something like "aerys.dev" to point on http://192.168.64.2:32502 the port defined in aerys host expose method should be 80 for aerys to work? since no port is defined in my browser "http://aerys.dev" and port numbers needs to match. I really like to avoid to listening on port 80.

**Comment by rdlowrey** [comment]
I actually have a similar issue inside docker containers on mesos+marathon so I need to resolve the container-on-cloud-infrastructure issue anyway :) will update ...

**Comment by rdlowrey** [comment]
@lukaszwit are you running multiple vhosts in your aerys setup or is there just the one? The reason I ask is because I think specifically there should be an optional server setting where if there's only one vhost in your aerys process (the normal use-case in cloud infrastructure) it doesn't bother to validate the exact host match and just sends all traffic to the single defined vhost in your aerys app.

**Comment by lukaszwit** [comment]
I will be happy to test the solution. Unfortunately I don't feel so strong with aerys internals to try PR ...yet ;)

**Comment by rdlowrey** [comment]
Yeah, so the culprit is this code block:

https://github.com/amphp/aerys/blob/5a2920902b2a554d85b0edad21d5050ee42a8f2c/lib/VhostContainer.php#L167-L177

If there's no exact hostname match (including the port number) the server falls through to that block if there's only a single host and tries to use the default vhost (so if there's only one vhost in the server that's always that default). But in this case the port number doesn't match and the end of line 175 fails.

I just need to add an option on the server that will optionally relax that check when there's only one vhost present ...

**Comment by rdlowrey** [comment]
There are some security concerns around how the virtual host is chosen based on the request's host header that impact this implementation. I'll be working on it and we should have something pushed that solves the problem over the weekend ... sorry you can't play with it right away :smile:

**Comment by bwoebi** [comment]
@rdlowrey Well, in particular, interfaces we don't intend to open to the public (but e.g. just an internal server) definitely must not be accessible generally.

So when there's a request for (let x being an IP) x:8000 on port 9000, we must not return the host bound to port 8000.

So, if there's an option we can set there, that should be fine too.

**Comment by rdlowrey** [comment]
Well, the real concern is actually that if you ignore incorrect host headers in determining the virtual host the user is requesting you open yourself up to injection vulnerabilities of which most server users will be unaware. Consider:

```
HTTP/1.1 GET /foo
Host: <script>alert("bar");</script>
User-Agent: script-kiddie-haxor
```

Now naive users run the risk of outputting the hostname in an effort to reconstruct the request URI:

```php
// OH NO!!!!
$uri = $request["headers"]["host"][0] . $request->uriPath;
```

This specific issue is a real problem in the PHP web SAPI where users blindly trust the `$_SERVER["SERVER_NAME"]` superglobal value which is **often** derived from the request's `Host` header without any knowledge on the part of the consumer of this value and assumed to be safe.

I spent a lot of time when writing the virtual host name matching code specifically to avoid problems like this (which are fully obviated if you correctly follow the HTTP spec and respond with 400 to requests with invalid host headers).

If you ignore requests for invalid hosts you avoid this problem. However, we see valid use cases for ignoring these minor differences in single host environments. So the challenge, then, is how to best account for both scenarios at once. That's what my forthcoming PR will aim to do.

**Comment by rdlowrey** [comment]
For completeness and to address the real underlying issue, @lukaszwit ...

Normally you'd want some sort of service discovery in your application ... that's how you should actually go about finding the mapped port for your server running on an ephemeral kubernetes instance. Folks frequently use etcd, consul, or zookeeper for this. 

You could simply ask your service discovery mechanism (these are beefed up, distributed key-value stores) for the address of your service and use that when building the aerys configuration. Aerys is like any other php file in that respect and you can do some bootstrapping operations of that sort in your config file.

**Comment by tyx** [comment]
Hello @lukaszwit ! It seems we have the same issue, any chance you find a workaround ?

**Comment by rdlowrey** [comment]
Sorry about the slowness here ... I'm about to be in-between jobs and should have some time to work on this :)

**Comment by kelunik** [comment]
It has just been mentioned here as a con, too. http://slides.com/ianlittman/yielding-higher-perf-php-10-15#/22

**Comment by far-blue** [comment]
coming late to the discussion but ran into this today - proxying to our code on a different port number caused things to fail. Having discussed this in the IRC channel, my suggestion would be to allow setting of ports() alongside a name() for a host. By default the bound port(s) would be used as is currently the case but where we want a vhost to be available via a proxy we can specify additional port numbers considered acceptable as long as the hostname matches.

In my case the server might be bound on port 8080 but I could also allow port 80 so proxying works.

@lukaszwit I believe Docker sets env vars for port mappings which you might be able to make use of. In environments such as Mesos, Kubernetes, Docker Swarm, Rancher and Nomad I'd strongly recommend Service Discovery services. I personally use Consul and rate it highly along with Registrator and Fabio.

**Comment by kelunik** [comment]
@lukaszwit @rdlowrey @far-blue @tyx You might want to have a look at the PRs #172 and #170.
