### ISSUE TITLE
disableKeepAlive = false doesn't work

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#126]
[`$disableKeepAlive`](http://amphp.org/docs/aerys/classes/options.html#disablekeepalive) doesn't work. Keep alive is always enabled.

**Comment by rdlowrey** [comment]
It _used_ to work :)

**Comment by rdlowrey** [comment]
I think we should instead control this with `$maxKeepAliveRequests = 0;` ... IMO there's no need to expose both options as setting the max to zero accomplishes the same thing. 

Only problem is the boolean logic in [this ternary](https://github.com/amphp/aerys/blob/master/lib/Server.php#L382) will prevent that from working. Changing `?:` to `??` should correct it.

**Comment by rdlowrey** [comment]
Okay so we're all on the same page, then. I think we could remove some ambiguity here by changing the name of `$maxKeepAliveRequests` to something like `$maxRequestsPerConnection`. Anybody have objections to that?
