### ISSUE TITLE
websocket lunch on remote host

### ISSUE THREAD

**Issue by mkeyno** [amphp/aerys#131]
hi, I'm sorry to open ticket for my question , but actually I'm not pro in php and with your instruction not figure out how to install it in my remote directory host , and really appreciate for couple of hints , in fact I've tried to hook url on my host to the Telegram webhoock call back bot, so at first step new update data inserted to MySQL database then websoket server give the update data to designated live client .
the problem is I bought the domain & host which is has Cpanel and I don't know how to configure my php server to lunch websocket service 
can you tell me which files should be copy in designated host URL and what files should be modified?
Thanks
My Cpanel images
[image](https://cloud.githubusercontent.com/assets/6232001/23093326/57fb941c-f5f5-11e6-82cc-33b0f8bb0195.jpg)

[image](https://cloud.githubusercontent.com/assets/6232001/23093360/e1f67326-f5f5-11e6-8ef8-290754664d77.jpg
)

**Comment by kelunik** [comment]
Aerys doesn't work like traditional PHP apps. It's an application server invoked via the command line interface (CLI). I'm not familiar with cPanel, but you need the ability to run command line scripts and keep them running in the background.

But if you want to use Telegram Webhooks, WebSockets aren't the thing you want. Webhooks are ordinary HTTP requests, no WebSockets involved.

**Comment by mkeyno** [comment]
@kelunik thanks for reply , I know but my domain is between  ESP module  and telegram bot , when telegram bot update new information by link mydomain/url/update.php then  server should pass this information to my module ,  module connected by websocket client service to my domain

**Comment by kelunik** [comment]
You will need some messaging system between your `update.php` and the Aerys WebSocket handler.

**Comment by kelunik** [comment]
@mkeyno If you have further questions, just reply, will reopen then.

**Comment by mkeyno** [comment]
sure ,   really appreciated @kelunik
