### ISSUE TITLE
Rename local variables for requests

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#138]
Currently we have `setLocalVar` and `getLocalVar`, I always disliked them, but couldn't come up with a better name. PSR-7 uses `getAttribute` / `withAttribute`, I think that's a really good name. I hereby propose to change the API: `getLocalVar` → `getAttribute` / `setLocalVar` → `setAttribute`.

**Comment by bwoebi** [comment]
Attribute? I think that's a bad name … It's not a property/attribute of the request, but a loosely tied local variable for individual usage.

**Comment by joshdifabio** [comment]
Metadata?

**Comment by kelunik** [comment]
This has been implemented in `0.8.x`.
