### ISSUE TITLE
Add --user command line option to aerys

### ISSUE THREAD

**Issue by marcioAlmada** [amphp/aerys#140]
AFAIK, and correct me if this is wrong, it's only possible to pass the user, from which workers will run, through a constant called `AERYS_OPTIONS`. Ex.:

```php
const
    AERYS_OPTIONS = [
        "user" => "marcio",
        "defaultContentType" => "application/json",
        ...
    ]
;
``` 

This is fine if you run from the same unprivileged user on all your dev and prod servers. But that can be a PITA if you need to set different users for different servers - because we obviously can not `getenv("MY_API_USER")` on a constant declaration in PHP.

I'd like to suggest a `-u` and `--user` option to aerys command line interface for that purpose. The rational is simply convenience - at least I noticed the "user" option is the only one that will certainly vary and can't be getenved like the exposed port.

Thoughts?

**Comment by kelunik** [comment]
You can use `getenv` when using `define` instead of `const`, but a command line option is better here I guess.
