### ISSUE TITLE
Performance issues and benchmarking

### ISSUE THREAD

**Issue by torinaki** [amphp/aerys#142]
During benchmarking Aerys performance and comparing with existing non-blocking HTTP servers solutions ReactPHP and NodeJS I have found some issues that probably must be investigated.

1. Sometimes requests are very slow(perc. 99% = 226.93ms) that spoils overall performance picture, but mostly performance is pretty similar comparing with NodeJS.
2. There no big difference between reactors. For some reason native PHP reactor has almost same performance as reactors based on ev, libevent or php-uv extensions.
3. There are constantly sockets errors:
```
Socket errors: connect 0, read 3669, write 0, timeout 0
``` 

Complete report and benchmarks here:
https://github.com/torinaki/aerys-benchmark

**Comment by nikic** [comment]
FYI `-dxdebug.default_enable=0` does not disable xdebug. You have to completely unload the extension, e.g. by using `php -n` to run without ini file.

**Comment by bwoebi** [comment]
You are probably running into the connections being rejected, in particular have a look at `Options->connectionsPerIP` setting. It's set to 30 by default and tries to prevent too many inbound connections from a same source. (aka trivial DoS spam protection)

Try `const AERYS_OPTIONS = ["connectionsPerIP" => 100];`, which should lead to no connections being rejected.
I think we really need to document that more prominently for people doing benchmarks...

**Comment by torinaki** [comment]
@nikic thanks you for your comment. I have changed this in latest commit and gain x3 better performance for Aerys, but not for ReactPHP. I'm still in trying to come up with the solution what need to be tuned for ReactPHP to gain same performance. 

@bwoebi this solves the issue. Seems like I missed this option during review the source. Originally I was referencing on following documentation:
http://amphp.org/docs/aerys/
http://blog.kelunik.com/2015/10/21/getting-started-with-aerys.html
but it doesn't contain any notes about `connectionsPerIP` option.

Followin issues was solved.
> There are constantly sockets errors:

**Comment by kelunik** [comment]
@torinaki Now that you're running with `php -n`, OPCache is disabled as well. You could enable that via another command line passed option. The cache itself isn't important for Aerys, as everything stays in memory anyway, but the optimizations bring benefits, which are only applied by OPCache.

**Comment by bwoebi** [comment]
@torinaki Well, it's not documented in the tutorial, that's true … maybe I should. Currently it's just documented under http://amphp.org/docs/aerys/classes/options.html#connectionsperip

**Comment by trowski** [comment]
I noticed you were doing benchmarking with Mac OS. There's something about Mac OS that we haven't resolved where requests in Aerys always go to the same worker, thus using only one CPU core. I've had better results running in a VM running some flavor of Unix or Linux (usually Debian). I'd be interested in seeing some comparisons under Unix or Linux, as well as with the Amp v2 version of Aerys as soon as Amp v2 is tagged.

**Comment by torinaki** [comment]
@kelunik I have added comparison w/ and w/o OpCache and it add 2-12% performance boost.

@bwoebi I would be great to add some notes people who is interested in benchmarking.

@trowski I have addressed your comment and running benchmarks on Travis with Ubuntu 14.04.5 LTS. It is not best environment for benchmarking. I have noticed results number deviation between builds, but it is not significant. We can see overall picture. In future it can be easily migrated into dedicated environment.  

Please see PR and Travis-Ci that contains full report in bash output for three versions of PHP 7.0, 7.1 and Nightly:
https://github.com/torinaki/aerys-benchmark/pull/4

ReactPHP performing better than Aerys, but React doesn't support keep-alive yet. Keep-alive give huge performance boost. Currently Aerys and NodeJS have different keep-alive settings. It may affect performance. Not sure by seems by default NodeJS do not have any connections or time limits

**Comment by torinaki** [comment]
Also I want to try to add PHP OpCache version with JIT:
https://externals.io/thread/268
I guess we can get additional boost due to JIT usually optimize hot code very well.

**Comment by kelunik** [comment]
I'm closing this issue, as the main question has been resolved.
