### ISSUE TITLE
Investigate SNI and Host header mismatch behavior

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#143]
See https://twitter.com/hanno/status/859796242678902786

**Comment by bwoebi** [comment]
I am not sure why we are _not_ setting SNI_server_name for interfaces with only one vhost. (if it's not named, then sure. But when it has a name, we still ignore it… why?!)

**Comment by kelunik** [comment]
It seems like there's no way to get the indicated SNI server name, at least I couldn't find a way.

**Comment by kelunik** [comment]
Vhost have been removed, so closing this one.
