### ISSUE TITLE
Provide an easier way to spawn a single process server

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#149]
Would be cool to have an easier way to spawn a single process server. ReactPHP makes something like that pretty easy. Could for example be useful if you use it only to accept webhooks instead of a full-fledged production HTTP server, such as in a simple chat bot.

**Comment by bwoebi** [comment]
Isn't this already possible by http://amphp.org/aerys/classes/bootstrapper?

**Comment by kelunik** [comment]
@bwoebi Could you add an example into `./examples` to listen for HTTP requests in a process without using `./bin`?

**Comment by kelunik** [comment]
This has been solved with `initServer`.
