### ISSUE TITLE
daemonize

### ISSUE THREAD

**Issue by mitsh** [amphp/aerys#151]
Hello,

How can i run in daemon mode? Have you any parameter for this, like --daemonize?

Update: 
..if its not able to do that. could you tell me how i can start listening this?
i will write my own daemonize logic and share with you.
```
(new Host)->name('localhost')
     ->expose('127.0.0.1', 21002)
     ->use($router);
```

Thanks,

**Comment by bwoebi** [comment]
`-c` is for specifying config files?

What do you exactly mean with daemon mode? Setting PPID (parent process id) to 1?

What do you actually need that for? Typically you make it being run via supervisord or launchctl or whatever the OS provides as control mechanism for background daemons.

**Comment by mitsh** [comment]
i try to developing standalone daemon/service(without OS dependency).

i am using CentOS. i will try to do that. if you have any information about that, could you tell me?

Thanks a lot!

**Comment by kelunik** [comment]
@mitsh While it works, it wouldn't restart the service on reboots or crashes, it's probably not what you really want.

**Comment by mitsh** [comment]
@kelunik you are right! i don't want that let happen. thanks for your advice.

**Comment by kelunik** [comment]
You can develop your daemon just as normal and just have the OS dependency as one installation step, but not as actual dependency of the daemon. The daemon doesn't know anything about who watches it.

**Comment by kelunik** [comment]
Closing, as it's not the task of Aerys.
