### ISSUE TITLE
Add support for SNI

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#152]
I think we do not support SNI currently.

**Comment by bwoebi** [comment]
Am I missing something, or isn't that supported via https://github.com/amphp/aerys/blob/5a2920902b2a554d85b0edad21d5050ee42a8f2c/lib/VhostContainer.php#L203-L235?

**Comment by kelunik** [comment]
I don't see `SNI_server_name` anywhere in php-src, but I see `SNI_server_certs` there.

**Comment by bwoebi** [comment]
Right… See 7.0 UPGRADING.

> Removed "CN_match" and "SNI_server_name" SSL context options. Use automatic detection or the "peer_name" option instead.

So should be fine to just rename it to peer_name here?

**Comment by kelunik** [comment]
@bwoebi `peer_name` is for client-side, it has to use `SNI_server_certs`. It should really just use the `amphp/socket` API.

**Comment by bwoebi** [comment]
okay, the UPGRADING is misleading then………

**Comment by kelunik** [comment]
@bwoebi No, I think this code has just always been broken.

**Comment by kelunik** [comment]
SNI support has been implemented as part of `0.8.x`.
