### ISSUE TITLE
Change namespace to Amp\Aerys

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#153]
I think we should change the namespace to `Amp\Aerys` so it's consistent with all other packages.

**Comment by bwoebi** [comment]
mhm. Originally it was intended to have the high-level libraries (artax, aerys, ...) under their own top-level namespace for easier accessibility.

Well essentially, it will force users to write `use Amp\Aerys;` in all their files… currently it's possible to write `\Aerys\Response` - nice and concise. `\Amp\Aerys\Response` starts becoming quite long.

**Comment by kelunik** [comment]
No, it doesn't force anybody to write `use Amp\Aerys`, people usually just import classes directly, so they use `use Aerys\Request` currently and would just use `use Amp\Aerys\Request` then. Using a vendor namespace is actually a `MUST` in PSR-4.

**Comment by bwoebi** [comment]
That's news to me, that this is required. May you please quote it? I didn't find any such assertion in the PSR-4 document.

Also: you don't really want to just blindly import all classes … at best that's just going to confuse you what library it comes from.

**Comment by kelunik** [comment]
> The fully qualified class name MUST have a top-level namespace name, also known as a “vendor namespace”.

**Comment by bwoebi** [comment]
Yes, and that is _any_ prefix, like, in this case `Aerys`.

**Comment by staabm** [comment]
Changing it will also mean the whole userbase needs to adjust for 0 value?

**Comment by bwoebi** [comment]
I'm opting to reject this. At least at the current point there's no point in this, just large cost.
