### ISSUE TITLE
Overriding $logger variable in Bootstrapper

### ISSUE THREAD

**Issue by pawaclawczyk** [amphp/aerys#154]
Using variable `$logger` in config file, like here:
```
<?php

declare(strict_types=1);

require_once __DIR__.'/vendor/autoload.php';

use Aerys\Host;
use Aerys\Request;
use Aerys\Response;
use function Aerys\router;


$logger = null;

$router = router()->get("/", function (Request $request, Response $response) {
    $response->end("OK");
});

(new Host())->expose("*", `8080)->use($router);
```
causes `TypeError`
```
[2017-07-03 19:04:53] critical TypeError: Argument 1 passed to Aerys\Bootstrapper::init() must implement interface Psr\Log\LoggerInterface, null given, called in /Users/pwc/src/aerys-example/vendor/amphp/aerys/lib/Bootstrapper.php on line 60 and defined in /Users/pwc/src/aerys-example/vendor/amphp/aerys/lib/Bootstrapper.php:70
Stack trace:
#0 /Users/pwc/src/aerys-example/vendor/amphp/aerys/lib/Bootstrapper.php(60): Aerys\Bootstrapper->init(NULL, Array)
#1 /Users/pwc/src/aerys-example/vendor/amphp/aerys/lib/WorkerProcess.php(93): Aerys\Bootstrapper->boot(NULL, Object(Aerys\Console))
#2 /Users/pwc/src/aerys-example/vendor/amphp/aerys/lib/Process.php(44): Aerys\WorkerProcess->doStart(Object(Aerys\Console))
#3 /Users/pwc/src/aerys-example/vendor/amphp/aerys/bin/aerys-worker(83): Aerys\Process->start(Object(Aerys\Console))
#4 [internal function]: {closure}('a', NULL)
#5 /Users/pwc/src/aerys-example/vendor/amphp/amp/lib/Coroutine.php(81): Generator->current()
#6 /Users/pwc/src/aerys-example/vendor/amphp/amp/lib/Loop/Driver.php(119): Amp\Coroutine->__construct(Object(Generator))
#7 /Users/pwc/src/aerys-example/vendor/amphp/amp/lib/Loop/Driver.php(70): Amp\Loop\Driver->tick()
#8 /Users/pwc/src/aerys-example/vendor/amphp/amp/lib/Loop/EvDriver.php(147): Amp\Loop\Driver->run()
#9 /Users/pwc/src/aerys-example/vendor/amphp/amp/lib/Loop.php(53): Amp\Loop\EvDriver->run()
#10 /Users/pwc/src/aerys-example/vendor/amphp/aerys/bin/aerys-worker(84): Amp\Loop::run(Object(Closure))
#11 {main}
```

Run with PHP version:
```
PHP 7.0.20 (cli) (built: Jul  2 2017 18:16:56) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.20, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.17.3~mac-x64-zts70, https://blackfire.io, by SensioLabs
```

**Comment by kelunik** [comment]
`$logger` is a magic variable in the config and can be used to access (and change) the logger.

**Comment by bwoebi** [comment]
It would probably be better to transpose the `$logger` variable into e.g. `Bootstrapper::$logger` (public static var) for the duration of the inclusion. That way we reduce accidental overwrites while still providing access to it from within the config file.

**Comment by trowski** [comment]
We should allow different loggers on a host-by-host basis, perhaps add a `logger` method to `Host`, i.e.: `(new Host())->expose("*", 8080)->use($router)->logger($logger);` using the default instance if none is provided.

**Comment by bwoebi** [comment]
There is are a few problems with this:

- Bootables may be passed to multiple different Host::use(), but are only booted once.
- Not every log message is Host bound, some are interface bound (e.g. the accept() calls), some are also not even identifiable as being part of a certain host, in particular PHP errors (e.g. an E_WARNING) happening in some Coroutine.

It would be possible to only bind access logs to a specific callback/logger/whatever. But not really an option for everything else.

**Comment by kelunik** [comment]
We have refactored how config files work in `0.8.x`. They must return a closure that gets a `$logger` variable passed now as an argument. It should therefore no longer be possible to accidentally override it.

In addition, we plan to partly discourage using these config files, at least for users of containers. They should scale the number of containers instead and have only one process per container.
