### ISSUE TITLE
Redesign Middlewares

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#156]
The current middlewares are neither really useful nor developer friendly. They allow some transformation, but are tricky to write. They only thing that's currently easy enough is adding headers.

It's important to allow I/O and we definitely need a better API.

**Comment by assertchris** [comment]
It would be awesome to allow for easier ways to handle 4xx and 5xx errors. Currently, 404 is possible through an "anonymous" route. Perhaps we could have something similar for 405 and 500:

```php
$router->error(404, function($req, $res) { ... });
$router->error(405, function($req, $res) { ... });
$router->error(500, function($req, $res) { ... });
```

**Comment by bwoebi** [comment]
I'm not sure whether that's something the router can/should do.
Sure, the responses where they're generated within the control of the Router, sure.
But e.g. `Options->allowedMethods` may flat out reject the request before Router even gets involved. [By the way, then also middlewares aren't invoked either at that point.]

**Comment by assertchris** [comment]
Ok, but what about:

```php
$host->error(404, function($req, $res) { ... });
$host->error(405, function($req, $res) { ... });
$host->error(500, function($req, $res) { ... });
```

**Comment by bwoebi** [comment]
Right, that ;-) (the router can do it *too*, on top of it then).

At least I quite like that suggestion.

**Comment by assertchris** [comment]
At the host level, this also allows catching 404 errors after `root`, if `root` is registered after the router.

**Comment by kelunik** [comment]
See also #109.

**Comment by kelunik** [comment]
Middlewares have been renamed to `Filter` in a branch for the upcoming release. We'll introduce proper middlewares as part of the new request / response handling in #109.
