### ISSUE TITLE
Remove magic from Router

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#159]
Router currently converts any non-existent method to `route(strtoupper($method, ...$args))`. This should be removed, as any new method on `Router` is a potential BC break with that. Instead, people should just use `route("GET", ...)` instead of `get(...)`.

If we want, we can add shortcuts for the common methods, but I don't see too much advantage in that.

**Comment by kelunik** [comment]
@bwoebi Are you fine with explicit shortcuts for all common methods and removing the magic?

**Comment by bwoebi** [comment]
No.

I also don't buy that BC break argument. Yes, it's a theoretical BC break.
But really, it just doesn't look that great and typical highlighting is also putting focus on the strings, not the method names.

I am fine with removing it altogether instead. No replacement shortcuts. I would find it confusing if we allow _some_ shortcuts, arbitrarily chosen.

**Comment by kelunik** [comment]
> But really, it just doesn't look that great and typical highlighting is also putting focus on the strings, not the method names.

I don't get that, I just proposed to keep the shortcuts, but as explicit methods instead of `__call`.

> I am fine with removing it altogether instead. No replacement shortcuts. I would find it confusing if we allow some shortcuts, arbitrarily chosen.

I don't understand that either. You're for the shortcuts, but only if implemented with magic? They're not arbitrarily chosen, they'd be the well-known HTTP methods, i.e. `GET`, `HEAD`, `POST`, `PATCH`, `PUT`, `DELETE`, `OPTIONS`.

**Comment by bwoebi** [comment]
> You're for the shortcuts, but only if implemented with magic?

Yes. I do not like explicit shortcuts. I see no real benefit in disallowing shortcuts for arbitrary names except the few RFC'ed ones.

If you ask me, my preference is as said to just kill the __call alltogether without any replacement. We have route(). It's good enough. Simple and a single universal way.

**Comment by kelunik** [comment]
@bwoebi That's what I initially suggested and you were against that, but that's also my favorite solution.
