### ISSUE TITLE
onClose event for HTTP

### ISSUE THREAD

**Issue by ostrolucky** [amphp/aerys#161]
I am trying to take an action when client closes connection over HTTP. Meaning, I wish to do something when Server::close() is called. 

It seems aerys doesn't allow this, or am I wrong and there is a way? 

Only way I see is to enable assertions and provide custom logger which listens when message beginning with "close " is logged.

**Comment by kelunik** [comment]
Currently there's no way in directly listening to that event, what's your exact use case?

What you can do, is periodically writing something using `yield $response->write("\n")`, which will throw a `ClientException` if the client disconnected.

Maybe you're interested in joining the discussion in #109, which has also an open point for that.

> Only way I see is to enable assertions and provide custom logger which listens when message beginning with "close " is logged.

Creative!

**Comment by ostrolucky** [comment]
I am just streaming a file and would like to notify user when client aborted download. 

I guess I will give a chance to reactphp/http. On a brief look it's more mature and I can bind to all kind of events in their Socket class!

**Comment by kelunik** [comment]
Yes, exactly. You can also use a shortcut for that:

```php
try {
    yield Amp\ByteStream\pipe($handle, $response);
} catch (ClientException $exception) {
    // abort action
}
```
