### ISSUE TITLE
Make climate a suggested dependency

### ISSUE THREAD

**Issue by shouze** [amphp/aerys#162]
I wonder if any console/terminal requirement is necessary in this project except to make things prettier (but heavier vendor dir).

Should not be a required but a suggested dependency  no?

This way we should be able to add a replace rule in composer.json to avoid installing it.

**Comment by kelunik** [comment]
How does making it a non-dependency help you in creating a `replace` rule to avoid installing it? You can avoid that now already, if it's in suggest, it's not installed.

And no, it's not an optional dependency, it's also used for argument parsing.
