### ISSUE TITLE
Release Amp v2 version

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#164]
This issue is a meta-issue to track what's missing for an Amp v2 based release.

IMO we should implement all open issues in `v0.7.0` and release `v0.6.0` now.

**Comment by trowski** [comment]
I agree, releasing a `v0.6` with an API similar to `v0.5` would allow users of Amp v1 to more easily transition to Amp v2. `v0.7` can then include some of our proposed API changes.

**Comment by kelunik** [comment]
Anything missing or do you want to tag a release later today?

**Comment by bwoebi** [comment]
Yep, I agree as well; I'm not likely to work much on Aerys in the next few weeks … users would have to wait even more then.

Just release a v0.6 based on amp v2.
