### ISSUE TITLE
problems with demo.php

### ISSUE THREAD

**Issue by dpinol** [amphp/aerys#165]
Hi,
I have an isssue with the body2 endpoint of the demo.php (v0.6.0)
`[2017-08-20 20:01:24] error Error: Call to undefined method Amp\ByteStream\Message::advance() in /Users/dani/Dropbox/feina/php/vendor/amphp/aerys/demo.php:55`
My IDE also complain about getChunk in the posterior line.

What am I doing wrong?

thanks

**Comment by bwoebi** [comment]
Looks like demo.php is still using an older outdated API...

**Comment by kelunik** [comment]
@dpinol I just fixed `demo.php`.
