### ISSUE TITLE
Describe (or point to) routing syntax in Router class documentation

### ISSUE THREAD

**Issue by ncraike** [amphp/aerys#166]
The [`Router` class](https://amphp.org/aerys/classes/router) documentation doesn't describe the URL syntax available for dynamic routing, eg `/user/{name}/{id:[0-9]+}`.

I've now found the syntax described in the [HTTP API documentation](https://amphp.org/aerys/http#dynamic-routing), but that was after checking the `Router` page and then digging through the code for a while, because I thought it wasn't documented at all.

It'd be great to include the routing syntax in the [`Router` class](https://amphp.org/aerys/classes/router) page, or to at least link to the documentation on the [HTTP API](https://amphp.org/aerys/http#dynamic-routing) page.

**Comment by kelunik** [comment]
Thanks for the report, I've just added further text and links for the router docs.
