### ISSUE TITLE
pcntl_ functions disabled on ubuntu by default

### ISSUE THREAD

**Issue by staabm** [amphp/aerys#17]
not sure, if this is something we should worry about, but the default php.ini on my ubuntu 14 LTS, disallowed `pcntl_*` functions

```
mstaab:~/htdocs/aerystest/Aerys$ php bin/aerys -c examples/001_hello.ph           p
PHP Warning:  pcntl_signal() has been disabled for security reasons
```

Should throw a error with a hint for the user?

**Comment by kelunik** [comment]
I don't think they're disabled on Ubuntu by default. It may be your specific host. A ready script is still a good idea.

**Comment by staabm** [comment]
Its the default. Experienced it on ubuntu 12 and 14 lts

**Comment by kelunik** [comment]
I can't confirm that. It's disabled in `/etc/php5/apache2/php.ini`, but not in `/etc/php5/cli/php.ini`.
