### ISSUE TITLE
Add a ipc socket path configuration

### ISSUE THREAD

**Issue by shouze** [amphp/aerys#171]
As I want to run aerys into an immutable docker image container, would be cool to make socket configurable through config/options to make it predictable so I would be able to create the socket during the build of the docker image.

If this option is not set it could fallback to the actual behavior.

https://github.com/amphp/aerys/blob/f0ac1e3418bc3662bd0f91f99a2d308494bdb996/lib/WatcherProcess.php#L383

**Comment by kelunik** [comment]
Why do you need that one to be predictable?

**Comment by shouze** [comment]
because if you set the docker read only option to true at runtime, it enables a truly immutable container image protection so you can't write anything on your container filesystem at **anytime**. 

Thus this imply you have to be be able to pass the ipc socket path to aerys, this socket having to be created during the build of the docker image. Aerys should not be responsible of this socket creation, just to use an already existing one.

Ok so looks like a `-i` already exists at worker level so should be ok to propage this option to aerys console/bin?
https://github.com/amphp/aerys/blob/f0ac1e3418bc3662bd0f91f99a2d308494bdb996/lib/WatcherProcess.php#L467-L468

**Comment by kelunik** [comment]
Running completely in read only mode is probably no what you want, as it might break at any time, e.g. something might start swapping large streams onto the file system.

I'd recommend to use something like `docker run -d --read-only --tmpfs /run --tmpfs /tmp IMAGE`, see [here](https://www.projectatomic.io/blog/2015/12/making-docker-images-write-only-in-production/).

**Comment by shouze** [comment]
@kelunik yes I already knew about tmpfs, it's a good solution indeed for docker on your local machine or some container running on a single production host... but if you have a true production docker deployment at scale you probably have a cluster (swarm, k8s, mesos, ...).

In my case it's a swarm cluster and... guess what... tmpfs is not supported and will probably get never supported (you can't docker deploy on your swarm): https://docs.docker.com/compose/compose-file/#not-supported-for-docker-stack-deploy

So yes no `tempnam` or things like that for truly read only containers. There are other ways as usual to produce temporary things.

**Comment by kelunik** [comment]
While you can't use `--tmpfs` directly there, you can use `--mount type=tmpfs,destination=/app` according to https://docs.docker.com/engine/admin/volumes/tmpfs/.

**Comment by shouze** [comment]
Indeed, will give a try very soon, so will close this issue when I've checked it's working as expected.

**Comment by kelunik** [comment]
I'm going to assume it worked. If it didn't, please comment, so we can re-open the issue.

**Comment by shouze** [comment]
@kelunik I confirm that it works 👍

**Comment by kelunik** [comment]
:-)
