### ISSUE TITLE
worker process bootstrap hook before loop starts

### ISSUE THREAD

**Issue by brstgt** [amphp/aerys#174]
I need to use a custom loop but this is not possible with the current implementation of the worker script. I could set up a custom class with env var but
a) this is really hacky
b) our legacy project is not organized as a composer package and thus is not hooked in the vendor autoload so custom classes are not visible to the worker script

It would be good to have a possibility to use a bootstrap script like the config script but at early stages and should be quite easy to implement.

For explanation:
Custom loops can be helpful to e.g. measure time the loop spends in blocking activity or to decorate callbacks.

**Comment by kelunik** [comment]
You could define a `"autoload": { "files": ["..."] }` that calls `Loop::set()` which would be called before the loop is run.

**Comment by brstgt** [comment]
Would be an option, right. These autoloads would then apply to the whole project and not only to the worker process.

Are there arguments against having either a custom bootstrap and/or a customizable worker class?

**Comment by kelunik** [comment]
I'm just not seeing the use case yet, but maybe you can elaborate on that?
