### ISSUE TITLE
Don't apply IP restrictions to localhost

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#183]
Local IP addresses shouldn't be limited by default. This affects reverse proxies and benchmarks.

**Comment by bwoebi** [comment]
So, `127.0.0.0/8`, `::1` and `::ffff:7f00:0/104`?

Assuming you actually mean loopback addresses when saying _localhost_?

**Comment by staabm** [comment]
Maybe even all non routed privat adresses like 192.168... etc?

**Comment by bwoebi** [comment]
@staabm You're aware that there are quite a few ranges of these? (that starts getting expensive)

Also really depends on who is part of the private network you reside in. Only your own servers? Fine go for it. Other entities you cannot trust unconditionally? No. Private network just means not routed publicly on the internet.

**Comment by kelunik** [comment]
Maybe we should also disable compresson if the client is on a loopback address.

**Comment by kelunik** [comment]
Closing, as it has been implemented in `0.8.x`.
