### ISSUE TITLE
Generators from config file should handle promise returns correctly

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#188]
https://github.com/amphp/aerys/blob/7e01ef45b71303a8d5294b3ddbf0ed8f4760397b/lib/Internal/functions.php#L104

This should work if the return value of the generator is a promise. Either use `Amp\call` instead of `yield from` or remove the `else` from the other branch.

**Comment by krlv** [comment]
@kelunik Could you please provide an example where return value of the generator is a promise?
I'm trying to reproduce this use case, but constantly get `NULL` from generator.

**Comment by kelunik** [comment]
Fixed via #191.
