### ISSUE TITLE
There's no warning when the 'user' option is set to "root"

### ISSUE THREAD

**Issue by ztsu** [amphp/aerys#189]
There's a warning when server starts with `sudo`. But there isn't one when `user` option is set to `"root"` in `AERYS_OPTIONS`.

**Comment by bwoebi** [comment]
Not sure. Setting it to root means to me "I know what I'm doing".
Well, to be frank, you ought creating a separate process you communicate to via a socket which is then isolated to perform just the root-requiring operations. But sometimes doing that is overkill for your needs.

**Comment by ztsu** [comment]
Ok.

Should I close the PR?

**Comment by bwoebi** [comment]
If you agree with me, then yes, please close the issue and PR :-)

**Comment by ztsu** [comment]
Ok. Tanks. Sorry for taking you time :-)
