### ISSUE TITLE
Requests hang when process is started from aerys handler with HTTP 1.0

### ISSUE THREAD

**Issue by brstgt** [amphp/aerys#192]
With the attached config for aerys + nginx, requests hang if the following scenario happens:

- start nginx
- do NOT start aerys
- request a URL from nginx - will return with 502 
- start aerys
- all subsequent requests hang

[aerys-debug.zip](https://github.com/amphp/aerys/files/1364433/aerys-debug.zip)

NGINX config probably needs some adjustments for local paths + hostnames.
The problem das NOT occur if:
- aerys is requested directly, instead via nginx
- No artax download is done in the request handler
- Aerys does not deflate the response
- A static docroot handler is attached to aerys

... that's all I was able to find out until now. Sounds like a problem with the gzip chunks in the response.

**Comment by bwoebi** [comment]
Do you have some tcpdump data (including the raw application data in hex) of the request/responses (between nginx and aerys), so that I may try to reproduce it directly with the raw inputs?

Also, are you sure the problem is on the aerys side and not with nginx (just to exclude that possible error source)?

**Comment by brstgt** [comment]
A) no, no tcpdump yet. Raw app data can be seen in the example code

B) I cannot tell a 100% it's not an nginx problem. But it's less likely as
nginx has delivered a quadzillion requests in this universe and aerys has
not. But that doesn't mean it's not possible.

Am 08.10.2017 18:46 schrieb "Bob Weinand" <notifications@github.com>:

**Comment by bwoebi** [comment]
With raw app data I meant the application layer data of the tcpdump (so that you do not try to mask data which may cause me to not accurately reproduce it).

B) yes, but possibly it's some edge case with a particular response Aerys is delivering, that no other server happened to deliver to nginx yet.

**Comment by brstgt** [comment]
They payload does not matter. You can send whatever you want as long as it
is deflated. Curiously it only happens if artax is involved. I try to
reproduce it tomorrow with Niklas stream fixes. We'll see if it still
happens with them.

Am 08.10.2017 18:52 schrieb "Bob Weinand" <notifications@github.com>:

**Comment by kelunik** [comment]
@brstgt What's really strange is that the Artax response isn't even sent to the client, so Artax isn't really involved. Neither should the document root do anything there, except if you have a file in the document root named exactly after the request URI.

**Comment by brstgt** [comment]
Yes. I know. But it is reliably reproducible on our setup. We have this
issue in production and what I sent was the minimal setup to reproduce it

Am 08.10.2017 19:04 schrieb "Niklas Keller" <notifications@github.com>:

**Comment by bwoebi** [comment]
The issue is possibly related to the delay. I guess `yield new \Amp\Delayed(200);` will probably yield the same result then?

**Comment by brstgt** [comment]
I am almost 100% sure it is not barely related to a delay. We server
millions of requests per day with aerys and this case only happens since we
use artax for async file downloads and only in requests where we have artax
requests within a aerys request.
Of course, a can give it a try and dig deeper but I'd bet it is not only a
delay thing. Also it is not related to that single file in the example.

2017-10-08 19:12 GMT+02:00 Bob Weinand <notifications@github.com>:

**Comment by kelunik** [comment]
I can 100% confirm all observations. Adding a document root or removing Artax solves it. But also adding `proxy_http_version 1.1` solves it.

**Comment by brstgt** [comment]
I was able to track down the issue a bit more:

https://gist.github.com/brstgt/4b998bff0a603f6d19b36efbe0401d90

It happens not because of artax but because of the DNS resolution. It can be eliminated by setting a filesystem driver before doing the lookup.

And I was able to track it more in the code. Aerys does everything correct. In all cases the exactly same payload is written to the socket directly via fwrite in aerys/lib/Server.php:onWriteable

What is superstrange: When the problem occurs, the write buffer is not flushed which can be seen in tcpdump. It is only flushed
a) when the server shuts down
b) on a second request on the same socket (e.g reload page in browser with a aerys debug process)
c) apparently after a timeout. i observed it a couple of times but did not investigate

Also a fflush() after the fwrite() or a fclose() does NOT flush the socket.

With HTTP 1.1 it works. Even if it is not really requested as 1.1 but if only chunked encoding is enabled (manually in the code) within a 1.0 connection. I guess it's only because chunked encoding changes the payload what causes a socket flush for some weird reason.

**Comment by kelunik** [comment]
Chunked encoding shouldn't be enabled on a 1.0 response.

**Comment by brstgt** [comment]
Sure. I was debugging the cases.

**Comment by brstgt** [comment]
It seems to happen only if the worker pool of the resolver is started within an aerys request. Why:

- problem does NOT occur if ParallelDriver is initialized in aerys config
- problem DOES occur if the worker pool in ParallelDriver is started lazily on 1st use even though ParallelDriver is initialized in aerys config

**Comment by kelunik** [comment]
That explains also why it doesn't hang with adding a document root, because the document root creates the driver and uses it first then.

**Comment by brstgt** [comment]
Was able to break it down even more:

https://gist.github.com/brstgt/af56c08e1aba0d570524ff09e0ddac5c

It's definitely the proc_open that makes it hang

**Comment by kelunik** [comment]
This issue is related to `proc_open` doing a fork and inheriting handles. We can't do anything about that except for not using `amphp/parallel` for file system drivers right now.

PHP Bug Report: https://bugs.php.net/bug.php?id=70932

**Comment by kelunik** [comment]
We can just `stream_socket_shutdown` the socket for now, that makes the leaked FD useless and the connection close as expected.

**Comment by bwoebi** [comment]
So adding `@\stream_socket_shutdown($client->socket, \STREAM_SHUT_RDWR)` before:

https://github.com/amphp/aerys/blob/0f37694060886b97d47f084c4817322b56ada500/lib/Server.php#L857

fixes the whole issue too? If yes, then let's do that.

**Comment by kelunik** [comment]
Yes, I think so. At least ReactPHP shows exactly the behavior I expected once I removed it before `fclose`.

I think we don't have to care about legacy versions as ReactPHP does: https://github.com/reactphp/socket/blob/8a587454223eca3c8f1aa261fb09093784714368/src/Connection.php#L127-L133

This should also solve #182 then. I think it hangs, because the connection is still open, because of the fork.

**Comment by kelunik** [comment]
@bwoebi Could you add the fix?

**Comment by bwoebi** [comment]
Done

**Comment by kelunik** [comment]
@brstgt Could you verify the fix?

**Comment by brstgt** [comment]
@kelunik Yes, it works
