### ISSUE TITLE
Possibility to disable keep-alive timeout 

### ISSUE THREAD

**Issue by torinaki** [amphp/aerys#195]
I'm not sure about any practical need to disable keep-alive, but currently timeout header always persists in HTTP response. Just for consistency there should be possibility to disable timeout same as `maxRequestsPerConnection`.

Aerys reponse:
```
content-length:12
content-type:text/plain; charset=utf-8
date:Fri, 20 Oct 2017 13:27:43 GMT
keep-alive:timeout=9223372036854775807
x-powered-by:AerysServer
```
with following options:
```
const AERYS_OPTIONS = [
    'connectionTimeout' => PHP_INT_MAX,
    'maxRequestsPerConnection' => PHP_INT_MAX,
];
```

NodeJS response with default settings as example:
```
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 12
X-Powered-By: Node Server
Date: Fri, 20 Oct 2017 09:21:29 GMT
Connection: keep-alive
```

**Comment by bwoebi** [comment]
Well, I haven't done that due to there not being any practical need for this. If we don't timeout, you'll just risk running out of resources sooner or later.

I don't think somebody should set such a high connectionTimeout, ever. Nor that this should be done for the sake of consistency.

**Comment by kelunik** [comment]
Same here, I don't think there's a practical use case. One could argue that you might want to use something like that for Aerys behind a proxy, but there's no reason for that IMO. If your server is that idle, a re-established connection doesn't matter every X seconds, where X can be set large enough.

I don't think consistency with NodeJS is worth a change here.
