### ISSUE TITLE
Remove Response::flush

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#198]
IMO `Response::flush()` doesn't make a lot of sense. We should remove it. If you use `Response::stream()` you certainly want your contents to be flushed immediately instead of being buffered.

Opinions?

**Comment by bwoebi** [comment]
It depends on whether you are streaming few large chunks of data or rather many small ones (loops may cause this). Well, unless you want to shift any buffering responsibility onto the user.

Also, response flush is important for something like middlewares. E.g. the deflate filter relies on discovering how much data is going to be sent (Options->deflateMinimumLength). If we flush early, we cannot check that.

Thus, I would advise against dropping it.

**Comment by kelunik** [comment]
Yes, this should be the responsibility of the user. Things like `Amp\ByteStream\pipe` also don't call `flush()`.

No, flushing is not important for middlewares. It just complicates them. The deflate filter should just always compress streamed responses (if the content type matches) and ignore the minimum length, because in 99% of all cases a streamed response will be longer than the minimum length.

**Comment by bwoebi** [comment]
I disagree on the assumption that in 99% of the cases the streamed response will be longer. You just need a single frequent poll and your vast majority of requests will be actually very small. Or also: APIs (e.g. servers fetching for updates every so often).
It _is_ a valid assumption for full pages. But not for incremental updates.

Most middlewares will typically detach after the headers and not actually interact with the body data at all. And even if they do, false is trivially casted to an empty string. No issue here.

Usually you don't want to care whether a stream gets flushed or not. That's typically at the discretion of the underlying levels, unless you explicitly signal that. (e.g. on the TCP layer Nagle's algorithm is usually used - except if you explicitly communicate that you don't want it there.)

**Comment by kelunik** [comment]
> You just need a single frequent poll and your vast majority of requests will be actually very small. Or also: APIs (e.g. servers fetching for updates every so often).

How is the frequency related there?

> It is a valid assumption for full pages. But not for incremental updates.

Streaming doesn't make much sense for full pages, except for situations like reverse proxies. If you have incremental updates, your payload is 99% larger than 250 bytes.

> Most middlewares will typically detach after the headers and not actually interact with the body data at all.

That's also the only thing that's comprehensible for most people. Writing middlewares dealing with the response body is currently very challenging. See #156.

> TCP layer Nagle's algorithm

Note that Nagle's algorithms still sends small packets if all previous packets have been ACKed. It doesn't ever buffer contents that require further input to be sent.

**Comment by kelunik** [comment]
Closing, as it has been removed in the `0.8.x` branch.
