### ISSUE TITLE
How to invoke subrequests?

### ISSUE THREAD

**Issue by ivanjaros** [amphp/aerys#209]
I would like to perform subrequests in the route "controller". For example if I have payload that contains a single entry I will process it but in case it is a batch I would like to call the server internally for each of those entries so they can be a) processed separately and b) avoid having to write conditions and loops in order to process the batch in the same controller.

Is this possible?

**Comment by kelunik** [comment]
This is currently not that easy I guess. The best way would be calling your controller for each sub-request, instead of invoking the Aerys dispatch process.
