### ISSUE TITLE
Server shuts down before pending requests finished

### ISSUE THREAD

**Issue by brstgt** [amphp/aerys#210]
https://github.com/amphp/aerys/blob/01eb2287da55d20e759fc1b2933c853a1bcc662b/lib/Server.php#L434

I guess this should be 
```
if ($client->pendingResponses === 0) {
```

Client has no property "requestCycles"

**Comment by kelunik** [comment]
Maybe it should be `remainingRequests`? I'm not too familiar with that code.

**Comment by brstgt** [comment]
I don't think so. 'remainingRequests' says how many requests a client may process before being closed in keep-alive mode from what I can see.
During shutdown, you don't want to accept new requests. This is why remainingRequests is set to PHP_INT_MIN. Shutdown is complete when all clients have no pending responses (or shutdown times out).

**Comment by kelunik** [comment]
You're right, just had a quick look at the code around the line you mentioned. Seems weird that it uses `PHP_INT_MIN` instead of `0`.

**Comment by kelunik** [comment]
The corresponding PR has been merged, closing.
