### ISSUE TITLE
Multiple server in multi-core env

### ISSUE THREAD

**Issue by kixortillan** [amphp/aerys#220]
Hi is there a way for Amphp Aerys to run multiple server instances in different cores of a multi-core environment? Same as Nodejs Cluster. If you could guide me to this I am very thankful. Just new to this stuff and want to explore. I plan to use this along with Symfony to create a high concurrency app. I believe I can achieve that by using your other non-blocking libraries and this as a server and integrate it to symfony.

Thanks and keep up the good work :)

**Comment by kelunik** [comment]
Aerys does that by default if you run it with `vendor/bin/aerys -c config.php`. It uses as many workers as you have CPU cores by default. You can adjust the worker count with the `-w` switch.

**Comment by kixortillan** [comment]
Loved that response. Thank you very much!!

**Comment by kelunik** [comment]
I hope you have success in building your application!
