### ISSUE TITLE
Support application hot-reload

### ISSUE THREAD

**Issue by rdlowrey** [amphp/aerys#27]
Listen over local TCP loopback for hot reload commands (enable with a port number option switch passed to bin/aerys) or unix domain socket where available.

**Comment by kelunik** [comment]
We need also support for internal reload, so `Server::reload`.

**Comment by morrisonlevi** [comment]
Do we already have a protocol format for sending non-http messages to the server? I'm not aware of one, but this project has been moving really fast lately :D

**Comment by bwoebi** [comment]
No, we don't. We probably should end up doing something like `bin/aerys -c config.php --restart`, save an unix domain socket (or file with a random port number from the ephermal port range) to `"/tmp/".str_replace("/", "_", $config_path)` (we should be additionally able to guarantee that only one aerys instance of the same config runs now). Then we'll be able to use a very simple length-prefixed text protocol.

**Comment by bwoebi** [comment]
Fixed by #62.

**Comment by kelunik** [comment]
Where's `Server::reload`? ;-P

**Comment by bwoebi** [comment]
Use the `CommandClient` to stop all, to just restart the specific instance we already have `Server::doStop()`.
