### ISSUE TITLE
Add optionally automatic HTTP component parsing

### ISSUE THREAD

**Issue by rdlowrey** [amphp/aerys#30]
- Parse cookies into a request environment variable (similar to PHP's `$_COOKIE` but without the magic).

- Parse `multipart/form-data` request entity bodies into user-friendly arrays similar to the PHP web SAPI's `$_POST` and `$_FILES` superglobals.

**Comment by bwoebi** [comment]
We have cookie parsing, multipart form data is asked for in #43.
