### ISSUE TITLE
Transition configuration from Host::setAddress() -> Host::addAddress()

### ISSUE THREAD

**Issue by rdlowrey** [amphp/aerys#33]
It's currently difficult to bind a host on multiple IP interfaces. In particular, this makes it impossible to listening for connections on both IPv4 and IPv6 interfaces using the same host name impossible. The virtual host selection routine should be modified and the `Host` configuration API updated to allow for binding on multiple address interfaces with the same name.

**Comment by bwoebi** [comment]
Solved via 869ca49. `expose()` now doesn't overwrite, but allows adding you multiple interfaces.
