### ISSUE TITLE
Timeout connections that only send new lines

### ISSUE THREAD

**Issue by rdlowrey** [amphp/aerys#38]
Currently client connections can renew their "last-read data" timestamps between requests by sending new line characters which are (correctly) ignored by the server. Malicious users could abuse this feature to prevent timeouts and prevent other clients from connecting.

**Comment by bwoebi** [comment]
I doubt this will actually help much. You also can just specify a body length of 86400 and send each second a single char… voilà, connection blocked. IMHO not much you can do against this, except ratelimiting the connection number from a specific IP.

**Comment by noodlehaus** [comment]
Wouldn't a hard timeout limit be better for this?

**Comment by bwoebi** [comment]
noodlehaus, depending on your application, you'll want to allow big uploads, from eventually slow origins.  Hence a request taking an hour might be totally legitimate...

The important point as said, is ratelimiting the maximum number of simultaneous HTTP/1.1 connections to something like 1000.

**Comment by kelunik** [comment]
From a single origin? Something like 50 sounds way more reasonable.

**Comment by bwoebi** [comment]
@kelunik We're talking here about _accepting_ requests. (Or like half a megabyte of buffering) We obviously should not allow 1000 requests to be _dispatched_ simultaneously.

The main point here are proxys (or just a bunch of different endpoints sharing a same public IP). You don't want to just block it them off.

**Comment by bwoebi** [comment]
I determined this as not being a helpful countermeasure.
We have a limit of 30 connections / IP / worker currently, that should be enough.
