### ISSUE TITLE
Ability to add arguments for a config file

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#58]
Allow defining arguments that can be used in the config file, e.g.
- `bin/aerys -c config.php -- --port 80 --host localhost` or,
- `bin/aerys -c config.php --args port:80 --args host:localhost`

**Comment by bwoebi** [comment]
Pending issue upstream: https://github.com/thephpleague/climate/issues/73

**Comment by kelunik** [comment]
I guess we can just recommend to use environment variables as well.

**Comment by kelunik** [comment]
I think this should be solved with a configuration for the app instead of process arguments.
