### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#61]
And FastCGI, CGI, etc.

**Comment by bwoebi** [comment]
Reverse proxy via HTTP is done (see https://github.com/amphp/aerys-reverse); (Fast)CGI handlers still outstanding.

**Comment by kelunik** [comment]
Closing for now, as these are separate packages and should not be in core.

**Comment by torinaki** [comment]
@kelunik have you reviewed possibility to implement FastCGI as additional [HttpDriver](https://github.com/amphp/http-server/blob/32a3b0f97dc530179057fdcfad9b100efdca6c88/src/Driver/HttpDriver.php#L9)?
FastCGI implementation looks quite simple: https://github.com/PHPFastCGI/FastCGIDaemon/blob/master/src/Driver/Userland/ConnectionHandler/ConnectionHandler.php.
FastCGI lighter that HTTP and I assume that application server can benefit from that if we will use Nginx as the reverse proxy.
What do think?

**Comment by kelunik** [comment]
@torinaki Should be possible, yes. Please open a separate issue for that.
