### ISSUE TITLE
Properly review and ensure all limits

### ISSUE THREAD

**Issue by bwoebi** [amphp/aerys#64]
Especially HTTP/2 parser is still lacking some limit checking.
Also try to find potential DoS vectors.

P.s.: We first anyway need HashDos protection in PHP itself ...

**Comment by kelunik** [comment]
How about a checklist of limits here?

**Comment by bwoebi** [comment]
Current limits:

### Connections
- [x] maximum per IP
- [x] general limit

### HTTP message size
- [x] header size
- [x] body size
- [x] buffering limit

### HTTP 2
- [x] maximum of concurrent incoming streams

### HTTP output
- [x] soft cap on internal buffer size for streams

### HTTP connection timeout
- [x] keep alive timeout relative to last received or sent data (as long as not processing)

### Websocket message size
- [x] frame size
- [x] assembled frame (message) size

### Websocket throttling
- [x] bytes per unit of time
- [x] frames per unit of time

### Websocket connection timeout
- [x] maximum of missed "heartbeat" ping frames sent each few seconds
- [x] maximum waiting time for close frame acknowledgment

**Comment by kelunik** [comment]
Why do we have 128 KiB as request body default, but 2 MiB for websocket messages?

**Comment by bwoebi** [comment]
We allow 20 concurrent streams on HTTP/2 … the goal is to have a limit per connection.

**Comment by kelunik** [comment]
Can we close this?

**Comment by bwoebi** [comment]
Not sure. I'd really appreciate someone with experience in sec/DoS vector reviewing to give it a look though.

**Comment by kelunik** [comment]
I'm closing this issue for now, I don't think it's worth keeping it open.
