### ISSUE TITLE
websocket compliance with Autobahn

### ISSUE THREAD

**Issue by staabm** [amphp/aerys#65]
Make sure our websocket imlementation passes the Autobahn Testsuite

http://autobahn.ws/testsuite/
https://github.com/crossbario/autobahn-testsuite

**Comment by kelunik** [comment]
Autobahn doesn't compile for me.

**Comment by bwoebi** [comment]
Current tests should reflect most of Websocket protocol… If there's anything specific not yet tested here, please mention it...

**Comment by kelunik** [comment]
This issue is specifically about the autobahn tests and should not be closed until the test suite is used IMO.

**Comment by bwoebi** [comment]
There's no point in using the testsuite, as we are covering every testcase of the suite.

**Comment by kelunik** [comment]
It's a standard test suite, this seems point enough to use it.

**Comment by bwoebi** [comment]
Right, and that's why I implemented all of its tests in PHP.
