### ISSUE TITLE
Worker are restarted when stopping the server

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#67]
Workers are stopped but started again and directly stopped again before exiting while stopping the server with `ctrl + c`.

**Comment by bwoebi** [comment]
Can't reproduce… I've put some debug output into WorkerWatcher::spawn(), but it never was called after the ctrl+c (basically doStop() is called, but spawn() isn't, just as expected). The presence of the `$stopPromisor` property should prevent this precise situation.

**Comment by kelunik** [comment]
Seems to be fixed by the Amp update, but not sure yet. Will reopen once it happens again.

**Comment by kelunik** [comment]
Works most of the time, but just happened again two times.

**Comment by bwoebi** [comment]
The only possibility is a bad race condition… I'll push a probable fix shortly…

**Comment by kelunik** [comment]
Of course it's a race condition...
