### ISSUE TITLE
Websocket Upgrade not possible with Firefox

### ISSUE THREAD

**Issue by dol** [amphp/aerys#70]
Firefox sends the following Request on a Websocket upgrade [1]. The Rfc6455Endpoint implementation [checks](https://github.com/amphp/aerys/blob/b9c48a22d041293cbf1a25b7056d990ebff2c1db/lib/Websocket/Rfc6455Endpoint.php#L115)  if the Connection header to be exactly 'Upgrade'.
Firefox instead send ```Connection: keep-alive, Upgrade```. This will lead to an HTTP error response 426: ``` Bad Request: "Connection: Upgrade" header required'```

The [HTTP Connection header spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.10) allows more then one token for the header.

[1]
```
GET /ws HTTP/1.1
Host: localhost:1337
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Sec-WebSocket-Version: 13
Origin: http://localhost:1337
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: somerandom==
Connection: keep-alive, Upgrade
Upgrade: websocket
```

**Comment by kelunik** [comment]
Thanks for the report!
