### ISSUE TITLE
Using undefined variables

### ISSUE THREAD

**Issue by tpunt** [amphp/aerys#74]
Two variables (`$controlPayload` and `$dataPayload`) in `Rfc6455Endpoint::parser()` are not declared. It seems to be a problem from commit https://github.com/amphp/aerys/commit/b22c97c336052faf39b914054193a6a86e08f32b.

See: https://github.com/amphp/aerys/blob/2db42e2356f523ed796a87ceb8cdf75081d8e47b/lib/Websocket/Rfc6455Endpoint.php#L844-L847

**Comment by bwoebi** [comment]
Ehm, an use of a variable as a reference actually declares that variable.
I don't see where there's a problem?

**Comment by tpunt** [comment]
Ah, my bad... Clearly been a long day :L

**Comment by tpunt** [comment]
Actually, I maintain that there is something wrong with the code here. If you look at the linked commit, before the refactor the assign-by-ref was done to instance variables. After the refactor, they've simply been made local variables, but aren't used anywhere. So if the refactor has not affected functionality (and by the looks of it, it hasn't), then both of these assign-by-refs can be removed :)

**Comment by bwoebi** [comment]
Nah, that's fine, the way it is.

I'm basically having two buffers here and the reference chooses which of the two buffers is used … Their handling is identical, the RFC just requires separate buffers for data and control frames.

**Comment by bwoebi** [comment]
As an exercise, try removing that reference assignment and pipe data (without fin bit set) + control + continuation frame through the parser ;-)

**Comment by tpunt** [comment]
I'm guessing you've already tried that and it hasn't worked, so I think I'll leave it as-is :)

**Comment by bwoebi** [comment]
But I'll add a test which fails if we remove that… ;-)
