### ISSUE TITLE
How to connect via HTTPS?

### ISSUE THREAD

**Issue by sushi2k** [amphp/aerys#80]
Hi there,

I am trying to connect via HTTPS to aerys. I do have found a part in the code that enables TLSv1.0
https://github.com/amphp/aerys/blob/52e51e10c46f1fd73141fb8a916da401c7e3c112/lib/Vhost.php.

Nevertheless I am always getting a connection error with curl "curl: (35) Unknown SSL protocol error in connection to localhost:1337" when using HTTPS. Also without the HTTP2 flag in curl. 

How can I use HTTPS with aerys?

![screenshot at feb 11 22-10-37](https://cloud.githubusercontent.com/assets/5951320/12978512/4b9d0d54-d10c-11e5-8cd9-d30ab7484743.png)

**Comment by bwoebi** [comment]
What exactly does your config look like?

The strict minimum is using Host::encrypt() with a valid .pem filepath as argument.

**Comment by sushi2k** [comment]
Thanks for the hint. I changed the demo.php in the last line and added the encrypt function and the server is starting without problems. 

`
(new Host)->expose("*", 1337)->encrypt("/root/fuzzing/server/aerys/cert/server.cert")->use($router)->use($root)->use($fallback);
`

I also can now make a HTTPS request, but it's not using HTTP/2 as protocol, even if I enable it via curl. Any idea how to make HTTPS request via HTTP/2?

**Comment by kelunik** [comment]
Which OpenSSL version do you have? ALPN is only supported since `1.0.2`.

**Comment by sushi2k** [comment]
This is the version:

➜  ~  openssl version -v
OpenSSL 1.0.2f  28 Jan 2016

I can connect to other sites with curl that support HTTP/2 like google.com.

![screenshot at feb 12 14-34-01](https://cloud.githubusercontent.com/assets/5951320/13000473/ae1c6176-d195-11e5-92ba-dc7b94bfe755.png)

**Comment by kelunik** [comment]
Sorry, what's the OpenSSL version in your PHP build?

`php -r 'var_dump(OPENSSL_VERSION_TEXT);'`

@bwoebi We still have `Host::encrypt` which just accepts `$certificate` and `$options`? I thought I changed that… at least I wanted to. We should accept a separate `$key` and `$fullchain`.

**Comment by bwoebi** [comment]
@sushi2k Note this is negotiation over NPN (precursor to ALPN).

Are you sure your php binary is built on top of openssl 1.0.2+?

**Comment by sushi2k** [comment]
@kelunik: This is the output. 

![screenshot at feb 13 20-44-46](https://cloud.githubusercontent.com/assets/5951320/13027671/b01a6bd2-d292-11e5-9bda-c001a7c38b04.png)

@bwoebi: Thanks for the hint. Did also realize this after posting with NPN. As you can see from the screenshot above php is definitely built against openssl 1.0.2f. But you are right, my curl is built against OpenSSL/1.0.1.f. 

```
➜  /opt  curl --version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 nghttp2/1.7.1-DEV librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets
```

So I just build it against OpenSSL 1.0.2f and it's working now. Thanks for the support. 

![screenshot at feb 13 21-01-54](https://cloud.githubusercontent.com/assets/5951320/13027712/07d7fe00-d295-11e5-84af-c5a5e45e1874.png)

**Comment by bwoebi** [comment]
Version dependencies :-( Nice that you found your issue though!

Anyway, closing as issue solved.

**Comment by kelunik** [comment]
@bwoebi: How much work would NPN be?

**Comment by bwoebi** [comment]
@kelunik Very hard. There's no NPN support in ext/openssl.

Also HTTP/2 is officially requiring ALPN. There are some servers with a NPN fallback, but I guess that will be deactivated in a while anyway.
