### ISSUE TITLE
How to use Aerys as a library, without the aerys command?

### ISSUE THREAD

**Issue by toverux** [amphp/aerys#86]
Hello,

I'm sorry if that's a stupid question, but you're not explaining in the README or the documentation, how to use Aerys without its bootstrap command.

Well, right now I tried this:

```php
(new Host)
    ->expose('*', 4815)
    ->use(root(__DIR__.'/../../web'));

\Amp\run(function() {
    echo 'I see that message';
});
```

But that doesn't works. When I run `php myapp.php`, it exits immediately (but just prints my debug message). I don't even know if I'm missing something about Amp's internals or if that's a bug.

Happens with or without php-libuv.

Thank you!

**Comment by bwoebi** [comment]
Short answer: you don't.

What exactly are you trying to achieve?

There is one main reason why your script don't start Aerys but Aerys starts your script: Aerys also does process management internally (in non-debug), thus, it wants to fork and not execute your code in the master process, but only in workers.

There may be reasons (I haven't thought of) why you would manually like to control Aerys server, then I might provide an API to `Bootstrapper` class to run without separate config file?

Thanks for feedback :-)

**Comment by toverux** [comment]
I just want to integrate a HTTP server into an application that already does other things :)
For example, [reactphp/http](https://github.com/reactphp/http) or [ratchetphp/Ratchet](https://github.com/ratchetphp/Ratchet) could easily be added to an existing project. Plus, I'm not interested in Aerys' load balancing in this project, although it is a wonderful feature. And think about people who may want to use another load balancer ;)

**Comment by bwoebi** [comment]
This is not quite load balancing (in the sense of distributing over servers), but rather trying to evenly distribute load over cores (else you may end up with one core used to 100%, and the 7 cores are idling). (This is IMO a big shortcoming with ratchet or reactphp/http.)

But sure, I could decouple this ... did just now via 92505c6 (not yet tagged, use dev-master for now).

```PHP
\Amp\run(function() {
    $arrayOfAerysHostInstances = [...]; // see Aerys\Host documentation
    $arrayOfAerysOptions = [...]; // see Aerys\Options documentation
    $logger = new class extends Aerys\Logger {
        protected function output(string $message) {
            print "$message\n"; // log to stdout
        }
    };
    $server = (new Aerys\Bootstrapper(function() use ($arrayOfAerysHostInstances) {
        return $arrayOfAerysHostInstances;
    }))->init($logger, $arrayOfAerysOptions);

    $server->start(); // yields a Promise which gets resolved after complete startup
});
```

Then it's now your responsibility to balance load properly over your cores.

But you can execute as much code as you want inside the config file - just don't use Amp\run() manually (if using via bin/aerys). Inside the config file you are already in an Amp context. Example config file:

```PHP
(new Host)
    ->expose('*', 4815)
    ->use(root(__DIR__.'/../../web'));

\Amp\repeat(function() {
    // something's running asnyc each 5 seconds
}, 5000);
```

You do everything in your config file - except starting the loop itself.

**Comment by toverux** [comment]
Sorry for the late, I had no time to test it during these last 10 days.
Thanks a lot for addressing my problem - and I still think I'm not the only that had this idea =) (I really don't need balancing across cores, this is for a small service on a Raspberry Pi - I just needed a correct HTTP library, and yours seems excellent).
You should add a small link to this issue somewhere at the bottom of the readme ;)
Thanks again!
