### ISSUE TITLE
Garbage collecting

### ISSUE THREAD

**Issue by vuliad** [amphp/aerys#91]
Is there any proper way for collecting garbage?
Small example:
```php
(new Host)->use(
    function (\Aerys\Request $req, \Aerys\Response $res) {
        $redis = new Client("tcp://127.0.0.1:6379");
        $res->setHeader('Content-type', 'text/plain');
        $start = microtime(true);
        $readedData = yield $redis->get("foobar");
        $readedData=unserialize($readedData);
        yield $res->stream('Items: ' . count($readedData) . PHP_EOL);
        yield $res->stream('Time(s): ' . (microtime(true) - $start) . PHP_EOL);
        yield $res->stream('Memory(mb): ' . (memory_get_usage()/1024/1024));
        $redis->close();
    }
)->expose("192.168.56.102", 1337);
```
on high rate if i store something big to foobar(for ex. serialized data ~5mb) - memory usage increases very fast(and performance decreases).
Possible solutions are:
1) call gc_collect_cycles() on every request
2) call gc_collect_cycles() by timer (for ex. every second/minute)
Or there any other solutions?

**Comment by kelunik** [comment]
You need to call `$res->end()` for the response to end and be completely flushed. Additionally, you should have one redis connection, not one per request.

```php
$redis = new Client("tcp://127.0.0.1:6379");

(new Host)->use(
    function (\Aerys\Request $req, \Aerys\Response $res) use ($redis) {
        $res->setHeader('Content-type', 'text/plain');
        $start = microtime(true);
        $readedData = yield $redis->get("foobar");
        $readedData=unserialize($readedData);
        yield $res->stream('Items: ' . count($readedData) . PHP_EOL);
        yield $res->stream('Time(s): ' . (microtime(true) - $start) . PHP_EOL);
        yield $res->stream('Memory(mb): ' . (memory_get_usage()/1024/1024));
        $res->end();
    }
)->expose("192.168.56.102", 1337);
```

**Comment by bwoebi** [comment]
Calling `$res->end()` should not be required if you start the response. That's not an issue.
As @kelunik said, use one global redis connection, that solves your memory issue.

Though @kelunik could you please ensure redis to be cycle-free? (so that it doesn't fill gc root buffer?)

**Comment by kelunik** [comment]
@bwoebi It should be required, otherwise the response isn't ever ended correctly.

**Comment by bwoebi** [comment]
The response is automatically ended when the responder callable ends and the response had been started.

**Comment by bwoebi** [comment]
We may throw an exception instead there; but that's how it's currently at least.

**Comment by kelunik** [comment]
> Though @kelunik could you please ensure redis to be cycle-free? (so that it doesn't fill gc root buffer?)

I don't know where it should have cycles.

**Comment by vuliad** [comment]
> You need to call $res->end() for the response to end and be completely flushed. Additionally, you should have one redis connection, not one per request.

I tried this, but if i just press Ctrl+R - it still leaks very fast (tested on on 1-core vm).and, even i stop sending requests - memory not going down( only if i force gc_collect_cycles() )
I can create docker for this tomorrow - if it helps.

**Comment by kelunik** [comment]
It's always about the same for me, not increasing.

> Items: 1
> Time(s): 0.00036406517028809
> Memory(mb): 2.4064636230469

**Comment by kelunik** [comment]
@vuliad I can see the memory increasing with a new connection every time.

**Comment by bwoebi** [comment]
@vuliad It'd surprise me if you get a leak with @kelunik's code. If you instantiate a new Client each time, it will leak (until like you have done a few hundred or thousand of requests - i.e. when the gc root buffer is full - and then drop again).

**Comment by staabm** [comment]
Will the client automatically re-connect in case it looses the connection to the redis server while aerys is running?

**Comment by kelunik** [comment]
The normal client will, yes.

**Comment by vuliad** [comment]
Here it is: https://github.com/vuliad/amphp-test-docker
```bash
Setup:
cd /tmp/
git clone https://github.com/vuliad/amphp-test-docker.git
cd amphp-test-docker
docker build -t amphp-test .
docker run -d --name=amphp-test -v $(pwd)/project:/srv/project -p 1337:1337 amphp-test
docker exec -it amphp-test bash /srv/project/sh/run_native.sh
```

Result video: http://take.ms/1DqMy

**Comment by kelunik** [comment]
It's clearly an issue with Redis, should we move the issue to the other repository?

**Comment by kelunik** [comment]
@vuliad Can you verify, that the following works?

```php
<?php
$redis = new Amp\Redis\Client("tcp://127.0.0.1:6379");
$redis->set("foobar", str_repeat("a", 1024 * 1024 * 16));
echo "RUNNING".PHP_EOL;
(new Aerys\Host)->use(
    static function (\Aerys\Request $req, \Aerys\Response $res) use ($redis) {
        $res->setHeader('Content-type', 'text/plain');
        $start = microtime(true);
        $readedData = yield $redis->get("foobar");
        yield $res->stream('strlen: ' . strlen($readedData) . PHP_EOL);
        yield $res->stream('Time(s): ' . (microtime(true) - $start) . PHP_EOL);
        yield $res->stream('Memory(mb): ' . (memory_get_usage() / 1024 / 1024));
        $res->end();
    }
)->expose("0.0.0.0", 1337);
```

**Comment by vuliad** [comment]
@kelunik same result (

**Comment by kelunik** [comment]
You're right, don't know what I did there when I got other results with it.

**Comment by camspiers** [comment]
I can't reproduce this on OS X with PHP 7.0.6 and with the same versions of aerys and amphp/redis. Maybe it is an environment issue?

**Comment by kelunik** [comment]
@vuliad Could you please reopen the issue on `amphp/redis` with the correct reproduce script?
