### ISSUE TITLE
What's the right way to handle CORS preflight requests?

### ISSUE THREAD

**Issue by joshdifabio** [amphp/aerys#92]
When sending cross-domain requests, browsers [preflight](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests) non-GET requests with an OPTIONS request to determine the allowed HTTP methods. Is there an easy way to handle these requests when using `Aerys\Router`? If not, would it make sense to modify [`Aerys\Router`](https://github.com/amphp/aerys/blob/master/lib/Router.php#L68-74) in order to handle this?

**Comment by bwoebi** [comment]
OPTIONS requests fetch the Options->allowedMethods and return that. They are never routed to the router actually. Or do you need to access them yourself? Aerys\Router is adding the methods it uses itself to the allowedMethods. You should not need to manage these yourself.

**Comment by joshdifabio** [comment]
I'm seeing Aerys respond to OPTIONS requests with a 405 response, which doesn't work for CORS. Furthermore, CORS requires the `Access-Control-Allow-Methods` header to be set in the response to an OPTIONS request. Right now, I'm `use()`ing the following with my `Host` as a workaround, which works:

```php
function (\Aerys\Request $request, \Aerys\Response $response) use ($frontendUrl) {
    $response->setHeader('Access-Control-Allow-Headers', 'Content-Type');
    $response->setHeader('Access-Control-Allow-Origin', $frontendUrl)
    $response->setHeader('Access-Control-Allow-Credentials', 'true');
    if ($request->getMethod() === 'OPTIONS') {
        // todo find a proper solution to OPTIONS requests (belongs in the router)         $response->setHeader('Access-Control-Allow-Methods', 'GET, DELETE, PATCH, POST, PUT, OPTIONS');
        $response->end();
    }
}
```

Does this make sense?

**Comment by kelunik** [comment]
@joshdifabio You either need `$router->route("OPTIONS")` or manually add `OPTIONS` to the allowed methods as @bwoebi mentioned.

You can do something like `$router->options("{.*:path}", function ...);`.

**Comment by bwoebi** [comment]
@joshdifabio oh, sorry, I was confusing specific `OPTIONS /route` requests with generic `OPTIONS *` requests (which are handled by Aerys)

So, yes, like @kelunik suggested: `$router->options("/{path:.*}", function(...) { … })` to match all routes at once.

**Comment by joshdifabio** [comment]
```php
$router->options("/{path:.*}", $fn)
```

In the above example, is there some way I can get the allowed methods for the current URL inside `$fn`? Or are you suggesting I manually set the allowed methods myself based on the URL? (Bearing in mind the router already has this information.)

**Comment by bwoebi** [comment]
Hmm, technically it's possible (we'd just have to call `$fastRouteDispatcher->dispatch("", $ireq->uriPath);` - i.e. force it to return an METHOD_NOT_ALLOWED, which is accompanied by the method list) to get the allowed methods. It's just a quite expensive thing to run on each request (it matches against every present method) … not sure how to provide that best.

Do you have some suggestions how to inject a getter in some way here?

**Comment by bwoebi** [comment]
The only viable thing I can currently see is some public API method on Router with like `getUriMethods($uri): array`, then you `use ($router)` and execute that method with `strstr(Request::getUri(), "?", true)`

**Comment by kelunik** [comment]
@bwoebi I'm against it, too much overhead.

@joshdifabio Usually you already know all methods your app supports and just allow everything you use.  I didn't see anything yet that restricts options based on routes. I'm not even sure if it's origin or URL dependent, otherwise URL dependent getter for the allowed methods wouldn't even make sense.

**Comment by bwoebi** [comment]
@kelunik ehm… Overhead? It's your call whether you call it or not. We're just providing a public API method here.

**Comment by kelunik** [comment]
@bwoebi Yes, but I think it's the wrong thing to do. I don't see the use case for it. Preflight requests are definitely not.

**Comment by bwoebi** [comment]
@joshdifabio hmm, why exactly do you need a more precise Control-Methods, per route? The Control-Methods doesn't indicate what is available, but what can be called. As such you just may always send all methods which may be called and where not appropriate, add a specific route.

**Comment by joshdifabio** [comment]
Actually, you're right, I can't think of any reason it's necessary to the methods dynamically per-route. I think I'll just continue to use a separate middleware to apply all the CORS headers. Thanks, and sorry for the noise.
