### ISSUE TITLE
NGINX complains about invalid chunked responses

### ISSUE THREAD

**Issue by joshdifabio** [amphp/aerys#93]
I'm getting lots of errors from NGINX (which I am using as a proxy in front of Aerys). The errors are as follows: _upstream sent invalid chunked response while reading upstream_

This is affecting most if not all static files served by Aerys (using _root()_). I do not currently have the eio or uv extensions installed, so Aerys is using Amp's native blocking filesystem driver.

**Comment by kelunik** [comment]
Which `proxy_http_version` do you use? Does it go away if you use `proxy_http_version 1.1`?

**Comment by joshdifabio** [comment]
> Which `proxy_http_version` do you use? Does it go away if you use `proxy_http_version` 1.1?

Thanks for the quick response. I'm already using 1.1.

**Comment by joshdifabio** [comment]
I just realised that I misread some timestamps in my logs; this isn't happening very often in actual fact, it seems to be intermittent. I'll post again if I notice any kind of pattern.

**Comment by bwoebi** [comment]
@joshdifabio There has been no update on this since a three months. I'm going to close this; feel free to followup if you ever encounter this issue again, with more detail.

**Comment by joshdifabio** [comment]
No worries, will do.
