### ISSUE TITLE
Server has type declaration for Aerys\Logger instead of Psr\LoggerInterface

### ISSUE THREAD

**Issue by cspray** [amphp/aerys#96]
I would like to be able to pass in my own implementation of a logger to the Aerys Server. This would allow me to persist logs to file, in a non-blocking manner of course, or send logs for certain levels to error monitoring services, for example. Is there an internal implementation reason why this type declaration is for a concrete class and not the interface? If so I could be able to provide a PR with the appropriate work if the problem can be described.

By the way, I think Aerys is pretty damn awesome. Writing an async app being able to yield Promises was an enlightening moment and really helped me better understand generators. It makes me cringe now when I have to work in JS and the callbacks that you all-too-often have to deal with.

**Comment by kelunik** [comment]
I don't see any reason for this. Could you provide a PR to change the type declarations?

**Comment by bwoebi** [comment]
Thanks, merged in #97.
