### ISSUE TITLE
Ability to customize Logger instance used in bin/aerys

### ISSUE THREAD

**Issue by cspray** [amphp/aerys#98]
I currently run an Aerys server on a production environment. I have a very strong need to send logs to a management service and to send errors to an error monitoring service. I would like to replace the built-in logger with my own PSR compliant implementation. Currently the only real way to do this is to write my own executable that emulates bin/aerys and pass my own logging implementation. This is a very brittle solution as it may break with future updates to Aerys and I believe that Aerys should discourage overwriting this executable and provide a robust means to control what happens through Host configuration or command flags/options.

I feel that this functionality would be useful baked into Aerys. I would like to propose that `Host::use()` accept a `Psr\Log\LoggerInterface` that will be used in place of the built-in Logger if present. I am not opposed to other ideas to accomplish this and would be willing to submit whatever Pull Request is necessary to see this implemented.

Right now mostly I'm reaching out to see if the idea seems reasonable and if this is something the maintainers would like to see. If not, I will move forward with writing my own executable to start the Aerys server.

**Comment by bwoebi** [comment]
This is a good question. However the `Host::use()` solution is only useful for host specific loggers. What shall happen to logs from the master process for example? Or generic server specific logs (e.g. debug log, purely accepting a connection is not Host bound, but IP/port bound or startup/shutdown etc.).

Currently you can either replace the logger in bin/aerys or you could pipe the output of bin/aerys to a separate script monitoring it [It should be easily parseable as it's always in format `"[{$time}] {$level} {$message}\n"`].

I'm not opposed to Host specific loggers; but this isn't an universal solution though.

Ultimately, parsing the output of the logs, isn't this what you also do for things like apache or nginx where you cannot implant your own logger?

**Comment by bwoebi** [comment]
Also, if you want to log accesses in general, (I don't talk about internal errors now), you can just install a tiny callable on each host, where you can log that to a specific file wherever in whatever format you wish. This could be a possibly helpful library for Aerys users:

`$host->use(cspray\aerys\log("{ip} -- {method} {path}", "/path/to/my/file.log"))`

**Comment by cspray** [comment]
I thought about this being a Host specific logger and for my immediate use case it seems to be sufficient for my needs. However, I do believe that a universal solution would be better. My original thought would be to provide a new configuration that specifies the instance of logger to use. But that would make Aerys responsible for instantiating arbitrary objects and that seems like a bad idea or could get clunky very fast.

Perhaps the configuration option could take the name of a PHP file that returned a LoggerInterface instance? This way I could construct my Logger with whatever dependencies are necessary and Aerys isn't responsible for that.

And this is the first time I've encountered this problem. Other applications I've ran have had infrastructure already built up to support this when I came onto the project.

**Comment by bwoebi** [comment]
While certainly possible, I generally prefer non-invasive methods. The more is done from the exterior, the better.

From what I've read, e.g. for nginx there's a tool called ngxtop, which basically is parsing the logs to show activity. There are also other tools doing similar things with log files…

But apart from that, there is the `$logger` variable present when the config file gets included. You can even override that variable and use a custom logger instance there.

The only thing which, as said, doesn't work that way, is catching the output from the master.

**Comment by kelunik** [comment]
As @bwoebi already mentioned, there's the `$logger` variable that can be overridden.

Aerys follows the logging guidelines of a twelve factor app: http://12factor.net/logs. I think it's best to parse the output and send it to your other services then.

Apart from the Aerys logger, you can also pass your own loggers to your objects / closures, independent of the Aerys logger.

**Comment by cspray** [comment]
Thanks for the instructive and timely feedback. After reviewing the log section for 12factor.net I agree that the best solution appears to be to parse the log output and handle pushing to external services in a separate process. Since there's no real change required for Aerys I'll close this issue.

**Comment by kelunik** [comment]
@cspray If you want to, you could add a section to our docs with our solution then: https://github.com/amphp/amphp.github.io/tree/master/docs/aerys
